#!/usr/bin/env python3
"""Bundle src/openclaw_pipe_pkg/ fragments into the single-file openclaw_pipe.py
that Open WebUI deploys.

Why a hand-written concat and not stickytape/pinliner: OWUI stores a function as
one flat .py file and (a) reads the frontmatter docstring from the FIRST bytes and
(b) introspects a top-level `Pipe` class. Loader-based bundlers prepend boilerplate
(breaking (a)) and bury classes inside a runtime loader (breaking (b)). We only
bundle our OWN first-party fragments — third-party deps (websockets, cryptography,
pydantic) are provided by the OWUI runtime and stay as normal imports — so the
"bundle" is a deterministic ordered concatenation.

Usage:
  python3 build.py            # build -> openclaw_pipe.py (DEV-ONLY blocks stripped;
                              # this is the artifact real users install)
  python3 build.py --check    # build in memory, diff vs committed openclaw_pipe.py,
                              # exit 1 if they differ (drift guard for CI/deploy)
  python3 build.py --dev        # build -> openclaw_pipe.dev.py, DEV-ONLY blocks kept.
                              # Internal-only (ELI-24 cross-agent deploy coordination);
                              # gitignored, never distributed, rebuild before every
                              # dev deploy.
  python3 build.py --check-dev  # same drift guard, for the dev bundle
  python3 build.py --action        # build -> openclaw_status_action.py, the
                              # companion Action Function (see ARTIFACTS below)
  python3 build.py --check-action  # same drift guard, for the action artifact
"""
from __future__ import annotations
import sys
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parent
PKG = ROOT / "src" / "openclaw_pipe_pkg"


class Artifact(NamedTuple):
    """One buildable output: a frontmatter file + an ordered subset of
    fragments from PKG, concatenated into a single flat .py file. Multiple
    artifacts can (and do) share the same fragment files -- see ACTION's
    reuse of _prelude/identity/state/gateway, which is the whole point of
    keeping those as separate fragments rather than inlining them into
    pipe.py.

    NamedTuple, not @dataclass: install.py's own _rebuild_pipe_file (and
    this repo's install_action.py) load this module dynamically via
    importlib.util.module_from_spec + exec_module, which does NOT register
    the module in sys.modules the way a normal `import` does. @dataclass's
    class-processing internally does sys.modules.get(cls.__module__) to
    resolve forward-referenced annotations (this file uses `from __future__
    import annotations`), which raises AttributeError on None under that
    loading pattern -- confirmed live, this broke install.py's existing
    _rebuild_pipe_file the moment this class was added as a dataclass, even
    though install.py itself was never touched. NamedTuple has no such
    dependency and sidesteps the whole issue."""
    frontmatter: Path
    out: Path
    dev_out: "Path | None"
    module_order: tuple[str, ...]


# Fixed dependency order. Module-load statements (constants, asyncio.Lock(),
# logging.basicConfig) have no cross-module load-time references, so this order
# only needs to satisfy human readability, not import semantics.
PIPE = Artifact(
    frontmatter=ROOT / "src" / "frontmatter.txt",
    out=ROOT / "openclaw_pipe.py",
    dev_out=ROOT / "openclaw_pipe.dev.py",
    module_order=("_prelude", "identity", "state", "media", "emit",
                  "askuser", "gateway", "models", "pipe"),
)

# The status Action reuses the Pipe's connection/identity/formatting
# fragments verbatim (same files, not copies) and adds only its own
# "action" fragment. "emit" is included so the modal's numbers come from
# the exact same _build_usage_status_lines/_fmt_tokens logic the status
# line itself uses -- one source of truth, no risk of the two drifting
# apart. No dev/internal-tooling variant yet -- add a dev_out here if this
# artifact ever grows a devcoord-style need for one.
ACTION = Artifact(
    frontmatter=ROOT / "src" / "frontmatter-action.txt",
    out=ROOT / "openclaw_status_action.py",
    dev_out=None,
    module_order=("_prelude", "identity", "state", "gateway", "emit", "action"),
)

BANNER = (
    "# ==========================================================================\n"
    "# AUTO-GENERATED by build.py from src/openclaw_pipe_pkg/ -- DO NOT EDIT HERE.\n"
    "# Edit the fragments under src/openclaw_pipe_pkg/ and re-run: python3 build.py\n"
    "# ==========================================================================\n"
)

FRAGMENT_HEADER_PREFIX = "# ---"  # strip the per-fragment BUILD FRAGMENT banner

DEV_ONLY_START = "# DEV-ONLY-START"
DEV_ONLY_END = "# DEV-ONLY-END"


def _strip_fragment_banner(text: str) -> str:
    """Remove the leading 'BUILD FRAGMENT' banner block a fragment carries."""
    out_lines = []
    lines = text.splitlines(keepends=True)
    i = 0
    # skip a contiguous leading comment block that is the fragment banner
    while i < len(lines) and lines[i].startswith("# "):
        i += 1
    # skip one blank separator after the banner, if present
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    out_lines = lines[i:]
    return "".join(out_lines)


def _strip_dev_only(text: str) -> str:
    """Drop every '# DEV-ONLY-START' .. '# DEV-ONLY-END' block.

    Dev/internal-tooling-only code (e.g. cross-agent deploy coordination,
    ELI-24) lives in src/ so it's testable and reviewable in context, but
    must never reach the artifact real users install -- hence stripped here
    rather than gated at runtime.
    """
    out_lines = []
    skipping = False
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if stripped == DEV_ONLY_START:
            if skipping:
                raise ValueError(f"nested {DEV_ONLY_START} marker")
            skipping = True
            continue
        if stripped == DEV_ONLY_END:
            if not skipping:
                raise ValueError(f"{DEV_ONLY_END} without matching {DEV_ONLY_START}")
            skipping = False
            continue
        if not skipping:
            out_lines.append(line)
    if skipping:
        raise ValueError(f"unterminated {DEV_ONLY_START} marker")
    return "".join(out_lines)


def build(strip_dev_only: bool = True, artifact: Artifact = PIPE) -> str:
    """Assemble one artifact's frontmatter + fragments into a flat .py file.

    Defaults to PIPE so existing callers (install.py's
    ``mod.build(strip_dev_only=not dev)``) keep working unchanged."""
    frontmatter = artifact.frontmatter.read_text()
    if not frontmatter.endswith("\n"):
        frontmatter += "\n"
    parts = [frontmatter, "\n", BANNER]
    for mod in artifact.module_order:
        body = _strip_fragment_banner((PKG / f"{mod}.py").read_text())
        if strip_dev_only:
            body = _strip_dev_only(body)
        parts.append("\n\n")
        parts.append(f"# --- {mod} " + "-" * (70 - len(mod)) + "\n")
        parts.append(body.rstrip("\n") + "\n")
    result = "".join(parts)
    if not result.endswith("\n"):
        result += "\n"
    return result


def _check(out_path: Path, built: str, label: str) -> None:
    current = out_path.read_text() if out_path.exists() else ""
    if built != current:
        print(f"DRIFT: {out_path.name} is out of date vs src/. Run: python3 build.py {label}",
              file=sys.stderr)
        sys.exit(1)
    print(f"{out_path.name} is in sync with src/ (no drift)")


def main():
    action = "--action" in sys.argv or "--check-action" in sys.argv
    dev = "--dev" in sys.argv or "--check-dev" in sys.argv
    checking = any(a in sys.argv for a in ("--check", "--check-dev", "--check-action"))

    if action:
        if dev:
            print("ACTION has no --dev variant yet", file=sys.stderr)
            sys.exit(2)
        artifact, out_path, label = ACTION, ACTION.out, "--check-action"
    else:
        artifact = PIPE
        out_path = PIPE.dev_out if dev else PIPE.out
        label = "--check-dev" if dev else "--check"

    built = build(strip_dev_only=not dev, artifact=artifact)

    if checking:
        _check(out_path, built, label)
        return

    out_path.write_text(built)
    print(f"built {out_path}  ({len(built.splitlines())} lines)")


if __name__ == "__main__":
    main()
