#!/usr/bin/env python3
"""Bundle src/openclaw_pipe_pkg/ fragments into the single-file openclaw_pipe.py
that Open WebUI deploys.

Why a hand-written concat and not stickytape/pinliner: OWUI stores a function as
one flat .py file and (a) reads the frontmatter docstring from the FIRST bytes and
(b) introspects a top-level `Pipe` class. Loader-based bundlers prepend boilerplate
(breaking (a)) and bury classes inside a runtime loader (breaking (b)). We only
bundle our OWN first-party fragments — third-party deps (websockets, cryptography,
pydantic) are provided by the OWUI runtime and stay as normal imports — so the
"bundle" is a deterministic ordered concatenation.

Usage:
  python3 build.py            # build -> openclaw_pipe.py
  python3 build.py --check    # build in memory, diff vs committed openclaw_pipe.py,
                              # exit 1 if they differ (drift guard for CI/deploy)
"""
from __future__ import annotations
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PKG = ROOT / "src" / "openclaw_pipe_pkg"
FRONTMATTER = ROOT / "src" / "frontmatter.txt"
OUT = ROOT / "openclaw_pipe.py"

# Fixed dependency order. Module-load statements (constants, asyncio.Lock(),
# logging.basicConfig) have no cross-module load-time references, so this order
# only needs to satisfy human readability, not import semantics.
MODULE_ORDER = ["_prelude", "identity", "state", "media", "emit",
                "askuser", "gateway", "models", "pipe"]

BANNER = (
    "# ==========================================================================\n"
    "# AUTO-GENERATED by build.py from src/openclaw_pipe_pkg/ -- DO NOT EDIT HERE.\n"
    "# Edit the fragments under src/openclaw_pipe_pkg/ and re-run: python3 build.py\n"
    "# ==========================================================================\n"
)

FRAGMENT_HEADER_PREFIX = "# ---"  # strip the per-fragment BUILD FRAGMENT banner


def _strip_fragment_banner(text: str) -> str:
    """Remove the leading 'BUILD FRAGMENT' banner block a fragment carries."""
    out_lines = []
    lines = text.splitlines(keepends=True)
    i = 0
    # skip a contiguous leading comment block that is the fragment banner
    while i < len(lines) and lines[i].startswith("# "):
        i += 1
    # skip one blank separator after the banner, if present
    if i < len(lines) and lines[i].strip() == "":
        i += 1
    out_lines = lines[i:]
    return "".join(out_lines)


def build() -> str:
    frontmatter = FRONTMATTER.read_text()
    if not frontmatter.endswith("\n"):
        frontmatter += "\n"
    parts = [frontmatter, "\n", BANNER]
    for mod in MODULE_ORDER:
        body = _strip_fragment_banner((PKG / f"{mod}.py").read_text())
        parts.append("\n\n")
        parts.append(f"# --- {mod} " + "-" * (70 - len(mod)) + "\n")
        parts.append(body.rstrip("\n") + "\n")
    result = "".join(parts)
    if not result.endswith("\n"):
        result += "\n"
    return result


def main():
    built = build()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if built != current:
            print("DRIFT: openclaw_pipe.py is out of date vs src/. Run: python3 build.py",
                  file=sys.stderr)
            sys.exit(1)
        print("openclaw_pipe.py is in sync with src/ (no drift)")
        return
    OUT.write_text(built)
    print(f"built {OUT}  ({len(built.splitlines())} lines)")


if __name__ == "__main__":
    main()
