"""
OpenClaw Status Action for Open WebUI
=======================================

A companion Action Function (separate from the OpenClaw Gateway Pipe) that
adds a button to the message toolbar. Clicking it fetches live session
context/usage data from the OpenClaw Gateway on demand -- not cached from
the last turn -- so it stays accurate even minutes after the last message.

Milestone 1 scope: proves the connection path works. Shows the result as a
toast notification. A richer dialog comes in a later milestone; this file
does not touch the Pipe or its existing status-line behavior at all.

How it works
------------
1. Reuses the Pipe's already-connected WebSocket connection when one exists
   (found via a stable OWUI module both Functions can read), so clicking
   this button opens zero new connections in the common case.
2. Falls back to its own connection only if the Pipe hasn't connected yet
   in this process. Still reuses the same on-disk device identity/token the
   Pipe already has (via STATE_DIR), so this never triggers a second
   device-pairing approval.
3. Calls the same read-only Gateway RPCs the status line uses
   (sessions.describe, usage.status), fresh on every click.

Requirements
------------
- Open WebUI v0.9+ (tested on v0.10.x)
- The OpenClaw Gateway Pipe (openclaw_pipe.py) installed in the same OWUI
  instance -- this Action is a companion to it, not a replacement
- Python modules: websockets, cryptography, pydantic (same as the Pipe)

Installation
------------
1. In Open WebUI, go to Admin Panel > Functions
2. Click "+" and choose "Create a function"
3. Set id to "openclaw_status_action" (type is auto-detected as "action")
4. Paste the entire contents of this file
5. Save and enable the function, then turn on the "Global" toggle so the
   button appears on every model's messages
6. Configure the valves (only needed for the fallback connection path --
   set them to the exact same values as the Pipe's valves):
   - GATEWAY_URL, GATEWAY_TOKEN, DEVICE_IDENTITY, STATE_DIR, AGENT_ID
"""

# ==========================================================================
# AUTO-GENERATED by build.py from src/openclaw_pipe_pkg/ -- DO NOT EDIT HERE.
# Edit the fragments under src/openclaw_pipe_pkg/ and re-run: python3 build.py
# ==========================================================================


# --- _prelude --------------------------------------------------------------

import asyncio
import json
import html
import os
import uuid
import logging
import base64
import time
import threading
import sys
import hashlib
import re
import mimetypes
import urllib.error
import urllib.request
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler
from dataclasses import dataclass, field

import websockets
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def pipe_log(*args):
    """Log to stdout so it appears in OWUI's backend logs."""
    print(f"[openclaw-pipe] {' '.join(str(a) for a in args)}", flush=True)

logging.basicConfig(level=logging.INFO, stream=sys.stdout)
logger = logging.getLogger(__name__)


# --- identity --------------------------------------------------------------

# ---------------------------------------------------------------------------
# Device Identity helpers
# ---------------------------------------------------------------------------

def _generate_device_identity():
    """Generate a fresh Ed25519 key pair and return a dict with id, publicKey,
    and privateKey (PEM)."""
    pk = ed25519.Ed25519PrivateKey.generate()
    pub = pk.public_key()
    raw = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw
    )
    pub_b64 = base64.urlsafe_b64encode(raw).decode().rstrip("=")
    did = hashlib.sha256(raw).hexdigest()
    pem = pk.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    ).decode()
    return dict(id=did, publicKey=pub_b64, privateKey=pem)


def _sign_challenge(ident, nonce, ts, token_str=""):
    """Sign the WebSocket challenge using the device identity."""
    parts = [
        "v2", ident["id"], "webchat", "cli", "operator",
        ",".join(GATEWAY_SCOPES), str(ts), token_str, nonce
    ]
    pk = serialization.load_pem_private_key(
        ident["privateKey"].encode(), password=None, backend=default_backend()
    )
    sig = pk.sign(("|".join(parts)).encode())
    return dict(
        id=ident["id"],
        publicKey=ident["publicKey"],
        signature=base64.urlsafe_b64encode(sig).decode().rstrip("="),
        signedAt=ts,
        nonce=nonce
    )


def _parse_device_identity(raw):
    """Parse DEVICE_IDENTITY JSON, handling unescaped newlines in PEM keys."""
    if not raw:
        return None
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    try:
        def _fix_pem(m):
            return m.group(1) + m.group(2).replace("\n", "").replace("\r", "") + m.group(3)
        fixed = re.sub(
            r'("privateKey":\s*")(.*?)("[, \\}])',
            _fix_pem, raw, flags=re.DOTALL
        )
        return json.loads(fixed)
    except Exception:
        return None


# --- state -----------------------------------------------------------------


def _state_dir(path=None):
    """Return the persistent bridge state directory, creating it if possible."""
    root = path or os.environ.get("OPENCLAW_BRIDGE_STATE_DIR") or "/data/openclaw-bridge"
    try:
        os.makedirs(root, mode=0o700, exist_ok=True)
        return root
    except Exception as ex:
        fallback = "/tmp/openclaw-bridge"
        os.makedirs(fallback, mode=0o700, exist_ok=True)
        pipe_log(f"STATE_DIR unavailable ({root}: {ex}); using {fallback}")
        return fallback


def _read_json_file(path):
    try:
        with open(path) as f:
            return json.load(f)
    except FileNotFoundError:
        return None
    except Exception as ex:
        pipe_log(f"Failed reading {path}: {ex}")
        return None


def _write_json_file(path, data):
    try:
        tmp = f"{path}.tmp"
        with open(tmp, "w") as f:
            json.dump(data, f, separators=(",", ":"))
        os.chmod(tmp, 0o600)
        os.replace(tmp, path)
        return True
    except Exception as ex:
        pipe_log(f"Failed writing {path}: {ex}")
        return False


# --- gateway ---------------------------------------------------------------
GATEWAY_SCOPES = ["operator.admin", "operator.read", "operator.write"]


# ---------------------------------------------------------------------------
# Custom exceptions
# ---------------------------------------------------------------------------

class GatewayError(Exception):
    """Raised when the Gateway WebSocket handshake fails."""
    pass


def _preview_recovery_text(preview: dict, session_key: str, user_text: str) -> str | None:
    """Return assistant text saved after this user message, if preview has it."""
    previews = preview.get("previews")
    if not isinstance(previews, list):
        return None

    entry = None
    for candidate in previews:
        if isinstance(candidate, dict) and candidate.get("key") == session_key:
            entry = candidate
            break
    if not entry:
        return None

    items = entry.get("items")
    if not isinstance(items, list):
        return None

    normalized_user_text = (user_text or "").strip()
    if not normalized_user_text:
        return None

    last_matching_user_index = None
    for idx, item in enumerate(items):
        if not isinstance(item, dict):
            continue
        if item.get("role") != "user":
            continue
        if str(item.get("text", "")).strip() == normalized_user_text:
            last_matching_user_index = idx

    if last_matching_user_index is None:
        return None

    for item in items[last_matching_user_index + 1:]:
        if not isinstance(item, dict):
            continue
        if item.get("role") != "assistant":
            continue
        text = str(item.get("text", "")).strip()
        if text:
            return text
    return None


def _owui_session_key(agent_id: str, user_id: str, chat_id: str) -> str:
    return f"agent:{agent_id}:openwebui-{user_id}-{chat_id}"


def _owui_chat_send_params(
    session_key: str,
    message: str,
    idempotency_key: str,
    owui_chat_id: str | None,
    owui_user_id: str | None,
) -> dict:
    params = dict(
        sessionKey=session_key,
        message=message,
        idempotencyKey=idempotency_key,
    )
    if owui_chat_id:
        metadata = {
            "chat_id": owui_chat_id,
            "source": "openwebui",
        }
        if owui_user_id and owui_user_id != "unknown":
            metadata["user_id"] = owui_user_id
        params["systemProvenanceReceipt"] = "\n".join([
            "Conversation info (untrusted metadata):",
            "```json",
            json.dumps(metadata, ensure_ascii=False, indent=2),
            "```",
        ])
    return params


def _resolved_model_key(patch_resp: dict) -> str | None:
    resolved = patch_resp.get("resolved", {})
    provider = resolved.get("modelProvider")
    model = resolved.get("model")
    if provider and model:
        return f"{provider}/{model}"
    return None


def _model_patch_matches(model_override: str | None, patch_resp: dict) -> bool:
    if model_override is None:
        return True
    return _resolved_model_key(patch_resp) == model_override


def _coerce_text(value) -> str:
    """Extract text from common stream payload shapes."""
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        for key in ("delta", "text", "content", "message"):
            text = _coerce_text(value.get(key))
            if text:
                return text
        return ""
    if isinstance(value, list):
        parts = [_coerce_text(item) for item in value]
        return "".join(part for part in parts if part)
    return ""


def _content_has_image(raw_content) -> bool:
    """True if an OWUI message's `content` is a multimodal block list
    (P39) that includes at least one image_url block. `content` is a
    plain string for ordinary text-only messages -- only the list shape
    (sent when a user attaches an image) can carry one, so this returns
    False immediately for the common string case."""
    if not isinstance(raw_content, list):
        return False
    return any(
        isinstance(block, dict) and block.get("type") == "image_url"
        for block in raw_content
    )


def _item_assistant_text(data: dict) -> str:
    """Return visible assistant text carried by item/preamble events."""
    kind = str(data.get("kind", "")).strip().lower()
    if kind not in ("assistant", "message", "output", "preamble"):
        return ""
    for key in ("delta", "text", "content", "message"):
        text = _coerce_text(data.get(key)).strip()
        if text:
            return text
    return ""


def _item_delta_text(item_text: str, last_item_text: str, assistant_stream_text: str) -> str:
    """Compute the new text (if any) an `item` event adds beyond what's
    already been shown, either by a prior `item` event or by the regular
    `assistant` delta stream.

    Some item events of kind "message"/"output" echo the *complete* final
    assistant text (not just a genuine tool-preamble) — without this check
    that full text gets yielded a second time on top of what the assistant
    stream already delivered, duplicating the whole final message.
    """
    baseline = last_item_text or assistant_stream_text
    if not baseline:
        return item_text
    if item_text == baseline:
        return ""
    if item_text.startswith(baseline):
        return item_text[len(baseline):]
    return item_text


def _suppress_already_shown(delta: str, visible_message_text: str) -> str:
    """Final safety net against re-yielding text that's already been shown.

    `_item_delta_text`'s dedup baseline (`assistant_stream_text` or
    `last_item_text`) is a separate accumulator from `visible_message_text`
    and can drift from it — e.g. a provider's final catch-all event races
    an idle-timeout recovery cycle, or arrives after other text (tool
    blocks, recovered previews) has been recorded into
    `visible_message_text` without also updating `assistant_stream_text`.
    When that happens, `_item_delta_text`'s prefix check fails to match and
    it falls through to returning the *entire* cumulative text unchanged,
    which then gets appended a second time with no separator (P27,
    reproduced live 2026-07-10).

    `visible_message_text` is the true, complete record of everything
    already recorded for this turn, so checking whether `delta` is already
    its tail catches this regardless of which upstream baseline caused the
    false negative — without touching the primary dedup logic (so a
    genuine partial catch-up, which is never already at the tail, still
    yields normally).
    """
    if delta and visible_message_text.endswith(delta):
        return ""
    return delta


# ---------------------------------------------------------------------------
# Persistent Gateway Connection (singleton)
# ---------------------------------------------------------------------------

# Re-enabled 2026-07-11 after fixing the ANNOUNCE_SKIP-class bug: an
# internal protocol marker ("ANNOUNCE_SKIP", from the sessions_send
# announce-delivery mechanism) was being proactively delivered into a chat
# as if it were real assistant text, because `_last_assistant_text_from_preview`
# didn't distinguish user-facing text from internal markers that happen to
# flow through the same event stream. Fixed by filtering the documented
# silent sentinels (`_SILENT_SENTINELS`: ANNOUNCE_SKIP, NO_REPLY, no_reply)
# before treating preview text as deliverable — see that constant's
# docstring. The separate duplicate-identity issue (a live turn in an
# actively-used real chat getting proactively re-delivered) was already
# fixed by `was_delivered_live` and confirmed via timestamps to only have
# happened in the window *before* that fix was deployed, not after. Do not
# re-disable without updating this comment and PLAN.md P33 with the new
# incident.
PROACTIVE_DELIVERY_ENABLED = True


# Anchor for state that must be shared by *every* `_GatewayConnection` alive in
# this Python process — not just the current module's singleton. OWUI's function
# loader execs each redeploy into a brand-new module object with no teardown hook
# on the old one, so a connection left running by a previous deploy (a "zombie")
# keeps its own event loop and its own *private* bookkeeping dicts. That zombie
# still receives the Gateway's broadcast `final` events; with private bookkeeping
# it sees an empty `delivered_live`/`session_last_activity` for the session,
# wrongly concludes "nobody consumed this, the session is idle", and proactively
# re-writes the turn into chat history — even though the *live* connection just
# showed it to the open tab. That is the "*↳ Proactive message* on a live turn"
# / duplicate-branch (2/2) bug (P33, root-caused 2026-07-11). Stashing the
# liveness bookkeeping on `open_webui.socket.main` (OWUI's own stable module,
# never reloaded by our function) makes all connections — current and zombie —
# read and write the *same* dicts, so a turn shown live by any connection is seen
# as delivered by all of them, and proactive delivery only fires for turns no
# connection ever showed live (genuine cron/heartbeat/sessions_send wakes).
_SHARED_STATE_ATTR = "_openclaw_gateway_shared_state_v1"


def _shared_gateway_state() -> dict | None:
    """Return the process-global bookkeeping dicts shared across all
    `_GatewayConnection` instances, or None when not running inside OWUI
    (e.g. unit tests), in which case callers keep instance-local state so
    each test connection stays isolated."""
    try:
        import open_webui.socket.main as _owui_socket_main
    except Exception:
        return None
    state = getattr(_owui_socket_main, _SHARED_STATE_ATTR, None)
    if state is None:
        state = {
            "delivered_live": {},
            "delivered_proactive": {},
            "session_last_activity": {},
            "pending_proactive_debounce": set(),
        }
        setattr(_owui_socket_main, _SHARED_STATE_ATTR, state)
    return state


@dataclass
class _Consumer:
    """An active run consumer — its ``asyncio.Queue`` receives events."""
    session_key: str
    run_id: str
    queues: list[asyncio.Queue] = field(default_factory=list)


class _GatewayConnection:
    """Singleton persistent WebSocket connection to the Gateway.

    Maintains one WS connection, dispatches events to per-run queues, and
    auto-reconnects on disconnect with exponential backoff.
    """

    def __init__(self, valves_ref):
        # Weak reference to Pipe valves (re-read on each call)
        self._valves = valves_ref
        self._ws: websockets.WebSocketClientProtocol | None = None
        self._event_loop_task: asyncio.Task | None = None
        self._init_lock = asyncio.Lock()

        # Identity
        self._ident: dict | None = None
        self._device_token: str | None = None

        # Request-response futures (keyed by request id)
        self._pending_reqs: dict[str, asyncio.Future] = {}

        # Run consumers (keyed by f"{session_key}:{run_id}")
        self._consumers: dict[str, _Consumer] = {}

        # Reconnect state
        self._reconnect_attempt = 0
        self._max_backoff = 30  # seconds
        self._stopped = False

        # Next request id
        self._next_req_id = 1

        # Counter for the event loop
        self._event_count = 0

        # Proactive-delivery bookkeeping. When running inside OWUI these four
        # dicts/sets are the *same objects* for every `_GatewayConnection` in
        # the process (see `_shared_gateway_state`), so a turn shown live by
        # one connection is seen as delivered by all of them and a zombie
        # connection left by a previous deploy can no longer re-deliver a live
        # turn as a bogus "*↳ Proactive message*" (P33, 2026-07-11). Outside
        # OWUI (unit tests) each connection gets its own isolated dicts.
        _shared = _shared_gateway_state()

        # Dedup guard for proactive OWUI delivery (P33/ELI-17), keyed by
        # "session_key:run_id" so a retried/duplicated final event — or a
        # second (zombie) connection racing the same idle session — never
        # writes the same message into chat history twice.
        self._delivered_proactive: dict[str, bool] = (
            _shared["delivered_proactive"] if _shared is not None else {}
        )

        # Records, by "session_key:run_id", every *final* event that was
        # actually dispatched to a live consumer queue (i.e. genuinely shown
        # to an open browser tab, which persists it itself via OWUI's normal
        # client-side flow). If the Gateway later re-emits a duplicate/retried
        # final event for that same run_id after the tab's request has
        # closed, this identity check catches it precisely — unlike a
        # content-equality check, it can't false-positive just because two
        # unrelated turns happen to end with the same short text (e.g. "OK.",
        # "Done."), and unlike the debounce timer alone, it doesn't depend on
        # how long the session stays quiet afterward.
        self._delivered_live: dict[str, float] = (
            _shared["delivered_live"] if _shared is not None else {}
        )

        # Last time *any* consumer for a session was registered or
        # unregistered (P33/ELI-19 second incident, 2026-07-11). A bare
        # `has_any_consumer_for_session() is False` check is racy at
        # steering-leg / OWUI-request boundaries: a leg can unregister its
        # consumer the instant its HTTP request ends, and the browser tab
        # sends the *next* leg's request (e.g. answering an ask-user modal)
        # a few seconds later under a brand-new run_id. During that gap the
        # session has zero registered consumers yet is not actually
        # abandoned — a "final" event landing in that window used to get
        # proactively delivered as a duplicate into a chat the user was
        # still actively looking at. Recording the timestamp on every
        # register/unregister lets `session_idle_for` require a minimum
        # quiet period with zero consumers before trusting the session is
        # genuinely idle, which a few-second leg gap cannot satisfy. Shared
        # across connections so a zombie sees the live connection's consumer
        # register/unregister activity and treats the session as busy, not
        # idle.
        self._session_last_activity: dict[str, float] = (
            _shared["session_last_activity"] if _shared is not None else {}
        )

        # Sessions currently being watched by a debounce task waiting for
        # `session_idle_for` to clear (see `_maybe_deliver_proactive_after_debounce`).
        # Prevents spawning a second concurrent watcher for the same session
        # when multiple unmatched "final" events arrive close together —
        # which would otherwise let both watchers independently observe
        # idleness later and each call `_deliver_proactive_owui_message`
        # with a *different* run_id, defeating the per-run dedup guard. Shared
        # across connections so two connections (e.g. current + a zombie) never
        # each spawn their own watcher for the same session.
        self._pending_proactive_debounce: set[str] = (
            _shared["pending_proactive_debounce"] if _shared is not None else set()
        )

    # ── Public API ──────────────────────────────────────────────────

    async def ensure_connected(self):
        """Ensure the WS connection is up; connect/reconnect if needed."""
        if self._ws and self._event_loop_task and not self._event_loop_task.done():
            return
        async with self._init_lock:
            if self._ws and self._event_loop_task and not self._event_loop_task.done():
                return
            self._stopped = False
            await self._connect_and_start()
            if not self._event_loop_task or self._event_loop_task.done():
                self._event_loop_task = asyncio.create_task(self._event_loop())

    async def send_request(self, method: str, params: dict, timeout: float = 10) -> dict:
        """Send a request and wait for the response."""
        req_id = str(self._next_req_id)
        self._next_req_id += 1
        fut = asyncio.get_running_loop().create_future()
        self._pending_reqs[req_id] = fut

        try:
            await self._ws.send(json.dumps(dict(
                type="req", id=req_id, method=method, params=params
            )))
            return await asyncio.wait_for(fut, timeout=timeout)
        finally:
            self._pending_reqs.pop(req_id, None)

    def register_consumer(self, session_key: str, run_id: str) -> asyncio.Queue:
        """Register an event consumer queue for a (session, run) pair.

        Returns a new queue attached to the consumer. Multiple queues per
        consumer are supported for broadcast (used by steering).
        """
        key = f"{session_key}:{run_id}"
        consumer = self._consumers.get(key)
        if consumer is None:
            consumer = _Consumer(session_key=session_key, run_id=run_id)
            self._consumers[key] = consumer
            pipe_log(f"  registered consumer: {key[:60]}...")
        q = asyncio.Queue(maxsize=500)
        consumer.queues.append(q)
        self._touch_session_activity(session_key)
        return q

    def unregister_consumer(self, session_key: str, run_id: str, queue: asyncio.Queue | None = None):
        """Remove a consumer queue.

        If queue is given, only that queue is removed (broadcast mode).
        If queue is None, the entire consumer (all queues) is removed.
        """
        key = f"{session_key}:{run_id}"
        consumer = self._consumers.get(key)
        if consumer is None:
            return
        if queue:
            try:
                consumer.queues.remove(queue)
            except ValueError:
                pass
        if not consumer.queues or queue is None:
            del self._consumers[key]
        self._touch_session_activity(session_key)
        pipe_log(f"  unregistered consumer: {key[:60]}...")

    def _touch_session_activity(self, session_key: str):
        self._session_last_activity[session_key] = time.time()
        if len(self._session_last_activity) > 500:
            oldest_first = sorted(self._session_last_activity.items(), key=lambda kv: kv[1])
            for stale_key, _ in oldest_first[:250]:
                self._session_last_activity.pop(stale_key, None)

    def mark_delivered_live(self, session_key: str, run_id: str):
        """Record that this run's final event was just dispatched to a live
        consumer queue — i.e. genuinely shown to an open browser tab, which
        persists it itself via OWUI's own client-side flow. See
        `_delivered_live`'s docstring for why this is the precise signal to
        gate proactive delivery on."""
        key = f"{session_key}:{run_id}"
        self._delivered_live[key] = time.time()
        if len(self._delivered_live) > 500:
            oldest_first = sorted(self._delivered_live.items(), key=lambda kv: kv[1])
            for stale_key, _ in oldest_first[:250]:
                self._delivered_live.pop(stale_key, None)

    def was_delivered_live(self, session_key: str, run_id: str) -> bool:
        return f"{session_key}:{run_id}" in self._delivered_live

    def active_run_id_for_session(self, session_key: str) -> str | None:
        """Return the sole active run id for a session, if one is registered."""
        matches = [
            consumer.run_id for consumer in self._consumers.values()
            if consumer.session_key == session_key
        ]
        if len(matches) == 1:
            return matches[0]
        return None

    def has_any_consumer_for_session(self, session_key: str) -> bool:
        """True if *any* run (not just a specific run_id) currently has a
        live pipe() call registered for this session.

        Used to gate proactive delivery (P33/ELI-17/ELI-19): an event can
        fail to match `consumers_for_event` (e.g. its run_id belongs to a
        just-superseded steering leg, or it's a bare session-only event with
        zero or multiple session matches) while the session is still
        genuinely being serviced by an open browser tab under a *different*
        run_id. Proactive delivery must only fire when the session has no
        active consumer at all — otherwise it risks injecting a duplicate
        message into a conversation that's live right now (see 2026-07-11
        incident in PLAN.md P33).
        """
        return any(
            consumer.session_key == session_key
            for consumer in self._consumers.values()
        )

    def session_idle_for(self, session_key: str, min_idle_s: float = 120) -> bool:
        """True only if the session has had *zero* registered consumers for
        at least `min_idle_s` seconds (P33/ELI-19, second incident,
        2026-07-11).

        `has_any_consumer_for_session` alone is racy: it can momentarily
        read False in the gap between one leg's HTTP request ending
        (unregister) and the browser's next request for the same logical
        turn arriving (register) — a few seconds, not the minutes a
        genuinely abandoned session sits idle for. Requiring a sustained
        quiet period turns a race into a simple timing margin: a real
        steering/modal round trip resolves in low single-digit seconds,
        while a proactive wake (cron, heartbeat, bare sessions_send) has no
        pending browser request at all, so it always clears the bar.

        A session_key never seen by this connection (no register/unregister
        recorded — e.g. this is a fresh process, or the previous owner of
        this session was a now-reaped zombie connection) has no activity to
        race against, so it's treated as idle immediately.
        """
        if self.has_any_consumer_for_session(session_key):
            return False
        last_activity = self._session_last_activity.get(session_key)
        if last_activity is None:
            return True
        return (time.time() - last_activity) >= min_idle_s

    def parse_owui_session_key(self, session_key: str) -> tuple[str, str] | None:
        """Reverse `_owui_session_key`: extract (user_id, chat_id) from a
        session key this pipe built, e.g.
        "agent:main:openwebui-<user_id>-<chat_id>". Both ids are fixed-width
        36-char UUIDs, so a positional split resolves the ambiguity of a
        plain "-".split() (UUIDs themselves contain dashes). Returns None for
        session keys not owned by this pipe/agent (e.g. cross-channel bleed).
        """
        agent_id = getattr(self._valves(), "AGENT_ID", None)
        if not agent_id:
            return None
        prefix = f"agent:{agent_id}:openwebui-"
        if not session_key.startswith(prefix):
            return None
        after = session_key[len(prefix):]
        if len(after) < 73 or after[36] != "-":
            return None
        return after[0:36], after[37:73]

    def consumers_for_event(self, payload: dict) -> list[_Consumer]:
        """Return consumers that should receive a Gateway event payload."""
        evt_session = payload.get("sessionKey", "")
        evt_run_id = payload.get("runId", "")
        if evt_session and evt_run_id:
            consumer = self._consumers.get(f"{evt_session}:{evt_run_id}")
            return [consumer] if consumer else []
        if evt_session and not evt_run_id:
            matches = [
                consumer for consumer in self._consumers.values()
                if consumer.session_key == evt_session
            ]
            return matches if len(matches) == 1 else []
        return []

    async def session_preview(self, session_key: str, limit: int = 8,
                              max_chars: int = 4000) -> dict:
        """Fetch a bounded transcript preview for timeout recovery."""
        return await self.send_request(
            "sessions.preview",
            dict(keys=[session_key], limit=limit, maxChars=max_chars),
            timeout=10
        )

    async def abort(self, session_key: str, run_id: str):
        """Send chat.abort for an active run."""
        try:
            await self._ws.send(json.dumps(dict(
                type="req", id="abort", method="chat.abort", params=dict(
                    sessionKey=session_key,
                    runId=run_id,
                )
            )))
            pipe_log(f"  sent chat.abort for run {run_id[:20]}...")
        except Exception as e:
            pipe_log(f"  abort send failed: {e}")

    async def send_stop(self, session_key: str):
        """Send the stronger /stop command for runtimes where chat.abort is incomplete."""
        try:
            resp = await self.send_request(
                "chat.send",
                dict(
                    sessionKey=session_key,
                    message="/stop",
                    deliver=False,
                    idempotencyKey=f"stop-{uuid.uuid4()}",
                ),
                timeout=10,
            )
            pipe_log(f"  sent /stop fallback: {resp}")
        except asyncio.TimeoutError:
            pipe_log("  /stop fallback timed out")
        except Exception as e:
            pipe_log(f"  /stop fallback failed: {e}")

    async def disconnect(self):
        """Gracefully close the connection."""
        self._stopped = True
        if self._event_loop_task:
            self._event_loop_task.cancel()
            try:
                await self._event_loop_task
            except asyncio.CancelledError:
                pass
            self._event_loop_task = None
        if self._ws:
            try:
                await self._ws.close()
            except Exception:
                pass
            self._ws = None

    # ── Internal ────────────────────────────────────────────────────

    async def _connect_and_start(self):
        """Connect, handshake, and start the event loop task."""
        valves = self._valves()
        parts = valves.GATEWAY_URL.rsplit(":", 1)
        host = parts[0]
        port = int(parts[1]) if len(parts) > 1 else 18789
        token = valves.GATEWAY_TOKEN

        if not token:
            raise GatewayError("No GATEWAY_TOKEN configured")

        # Device identity
        self._ensure_identity(valves)

        # Connect
        pipe_log(f"Connecting to ws://{host}:{port}")
        ws = await websockets.connect(f"ws://{host}:{port}", ping_interval=None)

        # Handshake: receive challenge
        challenge = json.loads(await asyncio.wait_for(ws.recv(), 10))
        if challenge.get("event") != "connect.challenge":
            raise GatewayError("Bad handshake — expected connect.challenge")

        c = challenge["payload"]
        signed = _sign_challenge(self._ident, c["nonce"], c["ts"], token_str=token)

        auth = dict(token=token)
        if self._device_token:
            auth["deviceToken"] = self._device_token

        await ws.send(json.dumps(dict(
            type="req", id="1", method="connect", params=dict(
                minProtocol=4, maxProtocol=4,
                client=dict(id="webchat", version="1",
                            platform="linux", mode="cli"),
                role="operator",
                scopes=GATEWAY_SCOPES,
                auth=auth,
                device=signed,
                locale="en-US",
                userAgent="openclaw-owui-pipe/1.0",
                caps=["agent-events", "tool-events"]
            )
        )))

        resp = json.loads(await asyncio.wait_for(ws.recv(), 10))
        if not resp.get("ok"):
            raise GatewayError(
                str(resp.get("error", {}).get("message", "connect failed"))
            )

        # Capture device token for future reconnects
        hello_ok = resp.get("payload", {})
        if hello_ok.get("auth", {}).get("deviceToken"):
            self._device_token = hello_ok["auth"]["deviceToken"]
            self._save_device_token(valves)
            pipe_log(f"Device token captured: {self._device_token[:20]}...")

        self._ws = ws
        self._reconnect_attempt = 0
        pipe_log("Connected to Gateway (persistent)")
        # NOTE: does not start/spawn the event-loop task — that happens
        # exactly once, in `ensure_connected`. This method is also called
        # from inside `_reconnect`, which runs from within the event-loop
        # task itself; spawning another task here would duplicate it.

    def _identity_path(self, valves):
        return os.path.join(_state_dir(getattr(valves, "STATE_DIR", "")), "identity.json")

    def _device_token_path(self, valves):
        return os.path.join(_state_dir(getattr(valves, "STATE_DIR", "")), "device-token.json")

    def _load_device_token(self, valves):
        if self._device_token:
            return
        data = _read_json_file(self._device_token_path(valves))
        if isinstance(data, dict) and data.get("deviceToken"):
            self._device_token = data["deviceToken"]
            pipe_log("Using persisted device token")

    def _save_device_token(self, valves):
        if not self._device_token:
            return
        _write_json_file(
            self._device_token_path(valves),
            {"deviceToken": self._device_token, "deviceId": self._ident.get("id")},
        )

    def _ensure_identity(self, valves):
        """Load or generate device identity from stable storage.

        Order matters for restart safety:
        1. state-dir identity file
        2. DEVICE_IDENTITY valve
        3. generate once and persist
        """
        if self._ident:
            return
        identity_path = self._identity_path(valves)
        ident = _read_json_file(identity_path)
        if ident and ident.get("id") and ident.get("privateKey"):
            self._ident = ident
            pipe_log(f"Using device identity from {identity_path}")
            self._load_device_token(valves)
            return

        if valves.DEVICE_IDENTITY:
            ident = _parse_device_identity(valves.DEVICE_IDENTITY)
            if ident and ident.get("id") and ident.get("privateKey"):
                self._ident = ident
                _write_json_file(identity_path, ident)
                pipe_log("Using device identity from valve and persisted it to state dir")
                self._load_device_token(valves)
                return
            pipe_log("Failed to parse DEVICE_IDENTITY valve; generating new identity")

        self._ident = _generate_device_identity()
        _write_json_file(identity_path, self._ident)
        pipe_log(f"Generated new device identity and saved it to {identity_path}")
        print(
            f"DEVICE_IDENTITY={json.dumps(self._ident, separators=(',',':'))}",
            flush=True
        )

    async def _event_loop(self):
        """Background task: reads WS messages and dispatches them.

        This is the ONLY task that ever calls `self._ws.recv()`. Reconnects
        happen in place (`self._ws = None`, then `_reconnect()` blocks until
        a new socket is ready) rather than by spawning a second event-loop
        task — spawning a second task here previously caused a runaway
        reconnect storm: the old coroutine kept looping after `_reconnect()`
        returned, so two tasks raced on `self._ws.recv()`, each collision
        raised its own exception, and each of *those* spawned yet another
        task (2026-07-10 incident, see PLAN.md P36).
        """
        while not self._stopped:
            try:
                if self._ws is None:
                    await self._reconnect()
                    continue
                msg = json.loads(await asyncio.wait_for(self._ws.recv(), timeout=90))

                # ── Request-response matching ──
                if msg.get("type") == "res":
                    req_id = msg.get("id")
                    fut = self._pending_reqs.get(req_id)
                    if fut and not fut.done():
                        if msg.get("ok") is False:
                            err = msg.get("error", {})
                            fut.set_exception(
                                GatewayError(
                                    err.get("message")
                                    or err.get("code")
                                    or "request failed"
                                )
                            )
                        else:
                            fut.set_result(msg.get("payload", {}))
                    continue

                # ── Tick keepalive (silently consume) ──
                if msg.get("event") == "tick" or msg.get("payload", {}).get("isHeartbeat"):
                    continue

                # ── Event dispatch ──
                if msg.get("type") != "event" or \
                   msg.get("event") not in ("agent", "chat"):
                    continue

                payload = msg.get("payload", {})
                consumers = self.consumers_for_event(payload)
                if consumers:
                    self._event_count += 1
                    if not payload.get("runId"):
                        pipe_log("  dispatched session-only event to sole consumer")
                    if payload.get("state") == "final" and payload.get("sessionKey") and payload.get("runId"):
                        # Genuinely shown to a live tab, which persists it via
                        # OWUI's own client-side flow — remember this so a
                        # later duplicate/retried final event for the same
                        # run_id is never proactively re-delivered (P33).
                        self.mark_delivered_live(payload["sessionKey"], payload["runId"])
                    for q in consumers[0].queues:
                        await q.put(msg)
                    continue

                # ── Proactive delivery for idle OWUI sessions (P33/ELI-17/ELI-19) ──
                # Nobody is live-consuming this *exact* event — no browser tab
                # is mid-request for this precise session+run. That alone is
                # NOT enough to prove the session is idle: this event's run_id
                # can simply not match a *different*, still-active run on the
                # same session (steering handoff, or a bare session-only event
                # with zero/multiple matches) — proactively delivering in that
                # case injects a duplicate into a live conversation (real
                # incident, 2026-07-11, see PLAN.md P33). Even
                # `has_any_consumer_for_session` alone isn't enough: it's a
                # point-in-time read that can be momentarily False in the gap
                # between one leg's HTTP request ending and the next leg's
                # request arriving a few seconds later (second 2026-07-11
                # incident). So this branch hands off to a debounce watcher
                # (`_maybe_deliver_proactive_after_debounce`) that only
                # delivers once the session has been genuinely consumer-free
                # for a sustained quiet period, not just at this instant. On
                # top of that, `was_delivered_live` gates out a *duplicate or
                # retried* final event for a run that was already genuinely
                # shown to a live tab — that scenario doesn't depend on
                # timing at all (the tab may have gone quiet for well over
                # the debounce window by the time the retry arrives), so it
                # needs its own identity-based check, not a longer timer.
                evt_session = payload.get("sessionKey", "")
                evt_run_id = payload.get("runId", "")
                if PROACTIVE_DELIVERY_ENABLED and evt_session and payload.get("state") == "final":
                    if (
                        self.parse_owui_session_key(evt_session)
                        and not self.has_any_consumer_for_session(evt_session)
                        and not self.was_delivered_live(evt_session, evt_run_id)
                        and evt_session not in self._pending_proactive_debounce
                    ):
                        self._pending_proactive_debounce.add(evt_session)
                        asyncio.create_task(
                            _maybe_deliver_proactive_after_debounce(
                                self, evt_session, evt_run_id
                            )
                        )
                        continue

                if payload.get("sessionKey") and not payload.get("runId"):
                    pipe_log("  dropped ambiguous or unmatched session-only event")

                # If nothing matches at all, drop it.
                # This efficiently filters cross-session bleed (P16).

            except asyncio.TimeoutError:
                # No events for 90s but connection is still alive
                continue
            except websockets.exceptions.ConnectionClosed:
                pipe_log("WS disconnected — reconnecting...")
                self._ws = None
            except asyncio.CancelledError:
                break
            except Exception as e:
                pipe_log(f"Event loop error: {e}")
                self._ws = None

    async def _reconnect(self):
        """Reconnect with exponential backoff.

        Blocks (looping in place, in the single `_event_loop` task) until a
        new connection is established or the connection is stopped. Must
        NEVER spawn a new `_event_loop` task — see the docstring on
        `_event_loop` for why that caused a runaway task/connection storm.
        """
        while not self._stopped:
            self._reconnect_attempt += 1
            delay = min(2 ** (self._reconnect_attempt - 1), self._max_backoff)
            pipe_log(f"  reconnect in {delay}s (attempt {self._reconnect_attempt})")
            await asyncio.sleep(delay)
            if self._stopped:
                return
            try:
                await self._connect_and_start()
                return
            except Exception as e:
                pipe_log(f"  reconnect failed: {e}")
                self._ws = None
                # loop and try again


# Protocol sentinels (docs/tools/subagents.md:470-431) that mean "no
# user-visible content was produced" — never real assistant text to show a
# human. An announce-follow-up run can legitimately finish with exactly one
# of these as its only "assistant text", and naively persisting it as a
# proactive OWUI message leaks internal plumbing into the chat (P33,
# 2026-07-11: `ANNOUNCE_SKIP` landed as literal message text).
_SILENT_SENTINELS = {"ANNOUNCE_SKIP", "NO_REPLY", "no_reply"}


def _last_assistant_text_from_preview(preview: dict, session_key: str) -> str | None:
    """Return the last assistant message text for session_key in a
    `sessions.preview` response (same shape `_preview_recovery_text` reads),
    without requiring a preceding user-text match — a proactive delivery
    (cron/heartbeat/sessions_send) has no live "user turn" in this pipe to
    anchor against, we just want whatever the run finished saying.
    """
    previews = preview.get("previews")
    if not isinstance(previews, list):
        return None
    entry = next(
        (p for p in previews if isinstance(p, dict) and p.get("key") == session_key),
        None,
    )
    if not entry:
        return None
    items = entry.get("items")
    if not isinstance(items, list):
        return None
    for item in reversed(items):
        if isinstance(item, dict) and item.get("role") == "assistant":
            text = str(item.get("text", "")).strip()
            if text and text not in _SILENT_SENTINELS:
                return text
            if text in _SILENT_SENTINELS:
                return None
    return None


async def _maybe_deliver_proactive_after_debounce(
    conn: "_GatewayConnection",
    session_key: str,
    run_id: str,
    min_idle_s: float = 120,
    poll_interval_s: float = 5,
    max_wait_s: float = 600,
) -> None:
    """Wait out `session_idle_for`'s quiet-period requirement before handing
    off to `_deliver_proactive_owui_message` (P33/ELI-19, second incident).

    Re-polls rather than sleeping once for `min_idle_s`, because the
    session's idle clock can restart at any point (a new leg registers a
    consumer, runs, then unregisters again) — a single fixed sleep would
    miss that and could still deliver during a live steering round trip. If
    the session never settles within `max_wait_s`, gives up rather than
    delivering into a session whose liveness can't be confirmed; also bails
    immediately if the kill switch is flipped back off mid-wait.
    """
    try:
        waited = 0.0
        while not conn.session_idle_for(session_key, min_idle_s=min_idle_s):
            if not PROACTIVE_DELIVERY_ENABLED:
                pipe_log("  proactive delivery: disabled mid-debounce, abandoning wait")
                return
            if waited >= max_wait_s:
                pipe_log(
                    f"  proactive delivery: session {session_key[:40]}... never "
                    f"settled idle within {max_wait_s:.0f}s, giving up"
                )
                return
            await asyncio.sleep(poll_interval_s)
            waited += poll_interval_s
        if conn.was_delivered_live(session_key, run_id):
            # The run got shown to a (re)connected live tab while we were
            # waiting out the debounce window — that tab already persists
            # it via OWUI's own client-side flow, so proactively delivering
            # now would be a pure duplicate.
            pipe_log(f"  proactive delivery: {session_key[:40]}... run "
                      f"{run_id[:20]}... was delivered live during debounce wait, skipping")
            return
        await _deliver_proactive_owui_message(conn, session_key, run_id)
    finally:
        conn._pending_proactive_debounce.discard(session_key)


async def _deliver_proactive_owui_message(
    conn: "_GatewayConnection", session_key: str, run_id: str
) -> None:
    """Persist a finished OpenClaw turn into OWUI chat history when nobody's
    tab is live-consuming it (P33/ELI-17: cron wake, heartbeat, or a bare
    `sessions_send` with no active `pipe()` call for this session+run).

    This only works because the pipe module is loaded as an OWUI function
    and runs inside OWUI's own backend process — the exact same in-process
    privilege `_retry_modal_on_reconnect` already relies on to import
    `open_webui.socket.main`. An external caller (e.g. a real OpenClaw
    channel plugin running in OpenClaw's own gateway process) has no
    equivalent access; OWUI does not expose a public API to both write a
    chat message and live-refresh an open tab for it, so v0 scope is
    persistence only — the message appears next time the chat is opened or
    refreshed, not instantly in an already-open tab.
    """
    parsed = conn.parse_owui_session_key(session_key)
    if not parsed:
        return
    user_id, chat_id = parsed

    dedup_key = f"{session_key}:{run_id}"
    if dedup_key in conn._delivered_proactive:
        return
    conn._delivered_proactive[dedup_key] = True
    if len(conn._delivered_proactive) > 200:
        for stale_key in list(conn._delivered_proactive)[:100]:
            conn._delivered_proactive.pop(stale_key, None)

    try:
        preview = await conn.session_preview(session_key, limit=1, max_chars=8000)
    except Exception as ex:
        pipe_log(f"  proactive delivery: session_preview failed: {ex}")
        return

    text = _last_assistant_text_from_preview(preview, session_key)
    if not text:
        pipe_log("  proactive delivery: no assistant text in preview, skipping")
        return

    text = f"*↳ Proactive message*\n\n{text}"

    try:
        from open_webui.models.chats import Chats
    except Exception as ex:
        pipe_log(f"  proactive delivery unavailable (not running inside OWUI process?): {ex}")
        return

    try:
        chat = await Chats.get_chat_by_id(chat_id)
        if chat is None:
            pipe_log(f"  proactive delivery: chat {chat_id[:8]}... not found")
            return
        history = chat.chat.get("history", {}) or {}
        old_leaf_id = history.get("currentId")
        new_message_id = str(uuid.uuid4())

        # `upsert_message_to_chat_by_id_and_message_id` unconditionally sets
        # `history.currentId = message_id` as a side effect of *every* call
        # (it's OWUI's own generic upsert, not something we control). So the
        # childrenIds patch on the *old* leaf must happen first — otherwise
        # it clobbers currentId back to old_leaf_id right after we set it,
        # and the new message becomes an invisible orphan branch (P33 bug,
        # found 2026-07-11: pipe_log showed successful "persisted" calls but
        # nothing ever appeared in OWUI, because currentId never actually
        # ended up pointing at the new message).
        if old_leaf_id:
            old_leaf = (history.get("messages") or {}).get(old_leaf_id, {})
            children = list(old_leaf.get("childrenIds", []))
            if new_message_id not in children:
                children.append(new_message_id)
                await Chats.upsert_message_to_chat_by_id_and_message_id(
                    chat_id, old_leaf_id, {"childrenIds": children},
                )

        await Chats.upsert_message_to_chat_by_id_and_message_id(
            chat_id,
            new_message_id,
            {
                "role": "assistant",
                "content": text,
                "parentId": old_leaf_id,
                "childrenIds": [],
                "timestamp": int(time.time()),
            },
        )

        pipe_log(
            f"  proactive delivery: persisted message into chat {chat_id[:8]}... "
            f"for user {user_id[:8]}... ({len(text)} chars)"
        )
    except Exception as ex:
        pipe_log(f"  proactive delivery failed: {ex}")


# Module-level singleton
_gateway_connection: _GatewayConnection | None = None
_gateway_init_lock = asyncio.Lock()

# Anchor for finding a connection left behind by a *previous* deploy of this
# same function (P33/P36: OWUI's function loader (open_webui/utils/plugin.py)
# execs each redeploy into a brand-new module object with no teardown hook on
# the old one — a module-level singleton alone resets every deploy and orphans
# the old module's WS/event-loop task forever). Stashing it as an attribute on
# `open_webui.socket.main` — OWUI's own stable module, never reloaded by our
# function — lets the next deploy find and `disconnect()` the previous one
# before opening a new connection, so redeploys self-heal without a container
# restart. Falls back to a no-op when not running inside OWUI (e.g. unit tests).
_STALE_CONN_ATTR = "_openclaw_gateway_connection_v1"


async def _reap_stale_gateway_connection() -> None:
    try:
        import open_webui.socket.main as _owui_socket_main
    except Exception:
        return
    stale = getattr(_owui_socket_main, _STALE_CONN_ATTR, None)
    if stale is None or stale is _gateway_connection:
        return
    try:
        await asyncio.wait_for(stale.disconnect(), timeout=5)
        pipe_log("  reaped stale gateway connection from a previous deploy")
    except Exception as ex:
        pipe_log(f"  failed to reap stale gateway connection (non-fatal): {ex}")


def _remember_gateway_connection(conn: _GatewayConnection) -> None:
    try:
        import open_webui.socket.main as _owui_socket_main
    except Exception:
        return
    setattr(_owui_socket_main, _STALE_CONN_ATTR, conn)


async def _get_gateway_connection(valves_getter) -> _GatewayConnection:
    """Get or create the singleton Gateway connection."""
    global _gateway_connection
    if _gateway_connection is not None:
        await _gateway_connection.ensure_connected()
        return _gateway_connection
    async with _gateway_init_lock:
        if _gateway_connection is not None:
            await _gateway_connection.ensure_connected()
            return _gateway_connection
        await _reap_stale_gateway_connection()
        conn = _GatewayConnection(valves_getter)
        await conn.ensure_connected()
        _gateway_connection = conn
        _remember_gateway_connection(conn)
        return conn


# --- emit ------------------------------------------------------------------


async def _emit_status(__event_emitter__, description, *, done=False):
    """Send an OWUI status event when the current pipe call supports events."""
    if not __event_emitter__:
        return
    await __event_emitter__(
        {"type": "status", "data": {"description": description, "done": done}}
    )


def _fmt_tokens(n) -> str:
    """Compact token count: 115212 -> '115k', 1000000 -> '1.0m'."""
    try:
        n = int(n)
    except (TypeError, ValueError):
        return "?"
    if n >= 1_000_000:
        return f"{n / 1_000_000:.1f}m"
    if n >= 1_000:
        return f"{n // 1_000}k"
    return str(n)


def _format_goal_line(goal: dict) -> str:
    """Mirror the TUI footer's goal phrasing (see docs/tools/goal.md)."""
    status = goal.get("status")
    tokens_used = goal.get("tokensUsed")
    budget = goal.get("tokenBudget")
    used_fmt = _fmt_tokens(tokens_used) if tokens_used is not None else "?"
    if status == "active":
        if budget:
            return f"🎯 Pursuing goal ({used_fmt}/{_fmt_tokens(budget)})"
        objective = (goal.get("objective") or "").strip()
        if len(objective) > 40:
            objective = objective[:39] + "…"
        return f"🎯 Pursuing goal: {objective}" if objective else "🎯 Pursuing goal"
    if status == "paused":
        return "🎯 Goal paused (/goal resume)"
    if status == "blocked":
        return "🎯 Goal blocked (/goal resume)"
    if status == "usage_limited":
        return "🎯 Goal hit usage limits (/goal resume)"
    if status == "budget_limited":
        return f"🎯 Goal unmet ({used_fmt}/{_fmt_tokens(budget)})"
    if status == "complete":
        return f"🎯 Goal achieved ({used_fmt})"
    return ""


def _window_bit(w: dict) -> str | None:
    used = w.get("usedPercent")
    if used is None:
        return None
    return f"{w.get('label')} {round(100 - used)}% left"


def _relative_time(reset_at_ms) -> str | None:
    """Compact relative countdown: '22m', '4h07m', '3d07h'. None if unknown/past."""
    if not reset_at_ms:
        return None
    delta_s = int((reset_at_ms - time.time() * 1000) / 1000)
    if delta_s <= 0:
        return None
    days, rem = divmod(delta_s, 86400)
    hours, rem = divmod(rem, 3600)
    minutes = rem // 60
    if days:
        return f"{days}d{hours:02d}h"
    if hours:
        return f"{hours}h{minutes:02d}m"
    return f"{minutes}m"


def _window_reset_line(w: dict) -> str | None:
    """Full detail line for one rate-limit window, only when it has a known
    reset time — e.g. '⏱ 5h 18% left (resets in 22m)'. Skipped for windows
    without a `resetAt` (e.g. Gemini's Pro/Flash aren't time-windows), since
    there'd be nothing new to say beyond what the thin combined line already
    shows.
    """
    bit = _window_bit(w)
    rel = _relative_time(w.get("resetAt"))
    if not bit or not rel:
        return None
    return f"⏱ {bit} (resets in {rel})"


async def _build_usage_status_lines(conn, session_key, timeout: float = 5) -> list[str]:
    """Best-effort final status lines: context window fill (combined with the
    provider's primary/nearest-term rate-limit window on the same line, kept
    deliberately thin — no reset time), one full detail line per rate-limit
    window that has a known reset time (e.g. both '5h' and 'Week' for
    Anthropic/OpenAI), and the active session goal (if any) on its own line.
    Returned as separate short lines (rather than one combined line) because
    OWUI's status UI hard-clamps every line to a single row (`line-clamp-1`,
    no way to disable per-event) — one line per fact keeps each row inside
    that clamp instead of getting cut off mid-number.

    OWUI shows only the *last* emitted status line by default (the rest
    only appear once the user expands that message's status history), so
    the thin context+primary-window line is placed last on purpose. Goal and
    the per-window reset-time detail lines still show up immediately on
    expand.

    Both RPCs are read-only and already used elsewhere by the pipe
    (`sessions.describe`) or are simple/cheap (`usage.status`); any failure
    here must not affect the actual reply, so every error is swallowed and
    just omits that line. They're fetched concurrently (not one after the
    other) so this adds at most one round trip's worth of latency, not two,
    to the moment the status line settles after the reply text is done.
    """
    describe_task = asyncio.ensure_future(
        conn.send_request("sessions.describe", dict(key=session_key), timeout=timeout)
    )
    usage_task = asyncio.ensure_future(conn.send_request("usage.status", {}, timeout=timeout))

    context_bit = None
    goal_line = None
    provider = None
    try:
        desc = await describe_task
        session_row = (desc or {}).get("session") or {}
        provider = session_row.get("modelProvider")
        context_tokens = session_row.get("contextTokens")
        total_tokens = session_row.get("totalTokens")
        if context_tokens and total_tokens is not None:
            pct = round(total_tokens / context_tokens * 100, 1)
            context_bit = f"🧠 {_fmt_tokens(total_tokens)}/{_fmt_tokens(context_tokens)} ({pct:g}%)"
        goal = session_row.get("goal")
        if goal:
            goal_line = _format_goal_line(goal) or None
    except Exception:
        pass

    primary_bit = None
    reset_lines = []
    try:
        usage = await usage_task
        if provider:
            for p in (usage or {}).get("providers", []):
                if p.get("provider") != provider:
                    continue
                windows = p.get("windows") or []
                bits = [b for b in (_window_bit(w) for w in windows) if b]
                if bits:
                    primary_bit = f"⏱ {bits[0]}"
                elif p.get("summary"):
                    primary_bit = f"⏱ {p['summary']}"
                # A full "(resets in ...)" line per window that actually has
                # a known reset time — including the same window already
                # folded into `primary_bit`, since that one stays thin (no
                # reset time) on purpose.
                reset_lines = [
                    line for line in (_window_reset_line(w) for w in windows) if line
                ]
                break
    except Exception:
        pass

    context_and_primary = " · ".join(bit for bit in (context_bit, primary_bit) if bit) or None

    return [line for line in (goal_line, *reset_lines, context_and_primary) if line]


async def _emit_message_snapshot(__event_emitter__, content):
    """Persist the in-flight assistant message content for OWUI reloads.

    Pipe yielded content is still the final source of truth, but OWUI only saves
    that content when the pipe completes. A short-name `replace` event updates
    the message content in the DB while the run is still active, so navigating
    away and back can rehydrate the partial response.
    """
    if not __event_emitter__ or not content:
        return
    await __event_emitter__(
        {"type": "replace", "data": {"content": content}}
    )


# --- action ----------------------------------------------------------------

# ---------------------------------------------------------------------------
# Milestone 1: prove a second OWUI Function can reach the OpenClaw gateway
# and read live session data, without disturbing the existing Pipe or its
# status-line code (emit.py / pipe.py are untouched by this fragment).
#
# Connection strategy, in order:
#   1. Reuse the Pipe's already-connected `_GatewayConnection` singleton.
#      The Pipe stashes it on `open_webui.socket.main` (a stable OWUI
#      module both Functions can import) purely so ITS OWN future redeploys
#      can find and clean up an orphaned previous connection -- see
#      `_STALE_CONN_ATTR` / `_remember_gateway_connection` in gateway.py.
#      This fragment only ever READS that attribute, never writes it: if we
#      also wrote there, whichever of {Pipe, Action} connected most
#      recently would silently "win" the slot, and the Pipe's own
#      `_reap_stale_gateway_connection()` could tear down a connection it
#      doesn't actually own on its next redeploy. Read-only avoids that
#      collision entirely.
#   2. If the Pipe hasn't connected yet in this process (e.g. right after a
#      container restart, before any chat turn happened -- in practice
#      unlikely, since this Action's button only appears above an existing
#      assistant message, which means the Pipe already ran at least once),
#      open our own connection. It still reuses the same STATE_DIR-persisted
#      device identity/token the Pipe already has, so this never triggers a
#      second `openclaw devices approve`. This fallback connection is owned
#      entirely by this module (its own singleton, never stashed on the
#      shared attribute) so it can never collide with the Pipe's bookkeeping
#      either.
#
# This fragment reuses gateway.py verbatim (see build.py's ACTION artifact),
# which includes `_event_loop()`'s proactive-message-delivery behavior: if a
# "final" event arrives on a connection with no registered consumer for its
# session, gateway.py writes the assistant's reply straight into OWUI chat
# history (see `_deliver_proactive_owui_message`). This Action never calls
# `register_consumer()` -- it only ever does request/response RPCs -- so a
# fallback connection would always look "idle" to that logic. In the
# reuse-the-Pipe's-connection path this is a non-issue (we're just borrowing
# a reference to make calls into an event loop the Pipe already owns and
# already registers real consumers on); it only matters for our OWN fallback
# connection's OWN event loop. Each build produces a fully separate Python
# module/namespace, so overriding this module-level flag here affects only
# this artifact's fallback connection, never the Pipe's.
PROACTIVE_DELIVERY_ENABLED = False

_action_fallback_connection: "_GatewayConnection | None" = None
_action_fallback_lock = asyncio.Lock()


async def _get_action_connection(valves_getter):
    """Return (connection, source) where source is "pipe" or "action-own"."""
    try:
        import open_webui.socket.main as _owui_socket_main
        pipe_conn = getattr(_owui_socket_main, _STALE_CONN_ATTR, None)
        if pipe_conn is not None:
            await pipe_conn.ensure_connected()
            return pipe_conn, "pipe"
    except Exception as ex:
        pipe_log(f"[status-action] could not reuse Pipe connection: {ex}")

    global _action_fallback_connection
    if _action_fallback_connection is None:
        async with _action_fallback_lock:
            if _action_fallback_connection is None:
                conn = _GatewayConnection(valves_getter)
                await conn.ensure_connected()
                _action_fallback_connection = conn
                return conn, "action-own"
    await _action_fallback_connection.ensure_connected()
    return _action_fallback_connection, "action-own"


# ---------------------------------------------------------------------------
# Milestone 2: a real dialog instead of a toast, rendered via the "execute"
# event (runs unsandboxed in the actual OWUI page, not a sandboxed Rich UI
# iframe) so it can use OWUI's own live Tailwind classes and CSS custom
# properties directly -- exact design-system match for free, no hand-tuned
# color palette, no guessing which of OWUI's several themes is active. The
# trade-off (unsandboxed JS) is acceptable here because the code is 100%
# admin-authored, not influenced by any untrusted input; the only dynamic
# values are our own gateway's numbers, passed in as a single JSON blob
# (never string-interpolated) so nothing can break out of the data payload.
#
# Split into two separate `execute` emits rather than one, for latency: a
# click should get instant visual feedback (the overlay + a loading
# skeleton), not nothing happening for however long the gateway round trip
# takes. `_MODAL_OPEN_JS` (static, no data, fired immediately) builds the
# overlay/panel/header/close-button and a placeholder body with a loading
# skeleton; `_render_modal_fill_js(data)` (fired once the RPCs resolve)
# finds that same body by id and replaces its contents in place -- no
# flicker, no second overlay animation. If the user already dismissed the
# dialog before the data arrived, the body element is gone and the fill
# call is a safe no-op (checked explicitly below).
# ---------------------------------------------------------------------------

_MODAL_OPEN_JS = r"""
(function() {
  const existing = document.getElementById('openclaw-status-modal-root');
  if (existing) existing.remove();

  const root = document.createElement('div');
  root.id = 'openclaw-status-modal-root';
  root.className = 'fixed inset-0 z-[9999] flex items-center justify-center';
  root.style.background = 'rgba(0,0,0,0.4)';

  const panel = document.createElement('div');
  panel.className = 'bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 '
    + 'rounded-2xl shadow-2xl border border-gray-100 dark:border-gray-800 '
    + 'p-5 w-[380px] max-w-[90vw]';
  panel.addEventListener('click', function(e) { e.stopPropagation(); });

  const header = document.createElement('div');
  header.className = 'flex items-center justify-between mb-3';
  const title = document.createElement('div');
  title.className = 'text-sm font-semibold';
  title.textContent = 'OpenClaw Status';
  header.appendChild(title);
  const closeBtn = document.createElement('button');
  closeBtn.type = 'button';
  closeBtn.textContent = '×';
  closeBtn.className = 'text-xl leading-none text-gray-400 hover:text-gray-700 '
    + 'dark:hover:text-gray-200 px-1';
  closeBtn.onclick = function() { root.remove(); };
  header.appendChild(closeBtn);
  panel.appendChild(header);

  const body = document.createElement('div');
  body.id = 'openclaw-status-modal-body';
  body.innerHTML = '<div class="animate-pulse space-y-2">'
    + '<div class="h-3 w-2/3 bg-gray-200 dark:bg-gray-700 rounded"></div>'
    + '<div class="h-3 w-full bg-gray-200 dark:bg-gray-700 rounded"></div>'
    + '<div class="h-3 w-1/2 bg-gray-200 dark:bg-gray-700 rounded"></div>'
    + '</div>';
  panel.appendChild(body);

  root.appendChild(panel);
  root.addEventListener('click', function() { root.remove(); });
  const onKey = function(e) {
    if (e.key === 'Escape') {
      root.remove();
      document.removeEventListener('keydown', onKey);
    }
  };
  document.addEventListener('keydown', onKey);

  document.body.appendChild(root);
})();
"""

# Static (no data), fired the moment a compact is triggered -- see
# Action._run_compact. Deliberately a distinct, prominent "Compacting..."
# state rather than reusing the generic loading skeleton: compaction is an
# LLM call that can take a while, so the dialog should look like it's
# doing something specific and ongoing, not like a normal fetch that's
# about to finish in a second.
_MODAL_COMPACTING_JS = r"""
(function() {
  const body = document.getElementById('openclaw-status-modal-body');
  if (!body) return;
  body.innerHTML = '';

  const isDark = document.documentElement.classList.contains('dark');

  const wrap = document.createElement('div');
  wrap.className = 'flex flex-col items-center justify-center py-6 text-center';

  const spinner = document.createElement('div');
  spinner.className = 'animate-spin rounded-full h-6 w-6 border-2 mb-3';
  spinner.style.borderColor = isDark ? '#4b5563' : '#d1d5db';
  spinner.style.borderTopColor = 'transparent';
  wrap.appendChild(spinner);

  const title = document.createElement('div');
  title.className = 'text-sm font-medium text-gray-700 dark:text-gray-200';
  title.textContent = 'Compacting…';
  wrap.appendChild(title);

  const sub = document.createElement('div');
  sub.className = 'text-xs text-gray-400 dark:text-gray-500 mt-1';
  sub.textContent = 'This can take a moment for long conversations.';
  wrap.appendChild(sub);

  body.appendChild(wrap);
})();
"""

_MODAL_FILL_JS_TEMPLATE = r"""
(function() {
  const DATA = __OPENCLAW_STATUS_DATA__;
  const body = document.getElementById('openclaw-status-modal-body');
  if (!body) return;
  body.innerHTML = '';

  const isDark = document.documentElement.classList.contains('dark');

  if (DATA.error) {
    const err = document.createElement('div');
    err.className = 'text-sm';
    err.style.color = isDark ? '#fb7185' : '#e11d48';
    err.textContent = DATA.error;
    body.appendChild(err);
    return;
  }

  // Used-percent -> color: green while healthy, amber approaching the
  // limit, red once it's mostly consumed. Same thresholds for every bar
  // (context and each rate-limit window) so the color language is
  // consistent across sections.
  //
  // Inline hex, not Tailwind utility classes: Tailwind only ships the
  // utility classes it finds referenced somewhere in ITS OWN build's
  // source, so a class this injected code invents (rather than one OWUI's
  // own frontend already uses) can silently have zero CSS behind it --
  // exactly what happened here. 'bg-rose-500' is never referenced
  // anywhere in open-webui/open-webui's own source (verified against the
  // real repo), so that utility class was never generated in OWUI's
  // compiled stylesheet at all; the fill div picked up the class but no
  // styling, rendering as an invisible 0-color bar even at 86% width.
  // 'bg-emerald-500' happened to render fine only because OWUI's own UI
  // elsewhere happens to use emerald -- relying on that coincidence for
  // every color is fragile (a future OWUI redesign could drop it too).
  // Inline styles have no dependency on the host page's Tailwind content
  // scan at all, so this can't recur regardless of what OWUI's frontend
  // does or doesn't use.
  function barColor(usedPercent) {
    if (usedPercent >= 85) return '#f43f5e';
    if (usedPercent >= 60) return '#f59e0b';
    return '#10b981';
  }

  function makeBar(usedPercent) {
    const track = document.createElement('div');
    track.className = 'h-1.5 w-full rounded-full overflow-hidden';
    track.style.backgroundColor = isDark ? '#1f2937' : '#f3f4f6';
    const fill = document.createElement('div');
    const clamped = Math.max(0, Math.min(100, usedPercent));
    fill.className = 'h-full rounded-full';
    fill.style.backgroundColor = barColor(usedPercent);
    fill.style.width = clamped + '%';
    track.appendChild(fill);
    return track;
  }

  function sectionHeader(text) {
    const h = document.createElement('div');
    h.className = 'text-[10px] font-semibold tracking-wide uppercase '
      + 'text-gray-400 dark:text-gray-500 mb-1.5';
    h.textContent = text;
    return h;
  }

  // Fetches back to this same Action (same-origin, unsandboxed execute
  // context -- no iframe/postMessage plumbing needed) with a synthetic
  // mode="compact" marker. Reads OWUI's own stored auth token directly
  // (confirmed against OWUI's frontend source: it keeps its bearer token
  // at localStorage['token']) rather than assuming cookie auth. The
  // chat/message/session identity is the *original* click's, threaded
  // through in DATA, so the Python side's __event_emitter__ calls for
  // this follow-up route back to this same open tab. The fetch response
  // itself is ignored -- all UI updates arrive as separate execute events
  // pushed from the Python side as the compact operation progresses,
  // exactly like the initial open/fill sequence.
  function triggerCompact() {
    const token = localStorage.getItem('token');
    fetch('/api/chat/actions/openclaw_status_action', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + token,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: DATA.owuiModel,
        chat_id: DATA.chatId,
        id: DATA.messageId,
        session_id: DATA.sessionId,
        mode: 'compact',
      }),
    }).catch(function(err) {
      const target = document.getElementById('openclaw-status-modal-body');
      if (!target) return;
      target.innerHTML = '';
      const errEl = document.createElement('div');
      errEl.className = 'text-sm';
      errEl.style.color = isDark ? '#fb7185' : '#e11d48';
      errEl.textContent = 'Could not start compact: ' + err;
      target.appendChild(errEl);
    });
  }

  const sub = document.createElement('div');
  sub.className = 'text-xs text-gray-500 dark:text-gray-400 mb-4';
  sub.textContent = DATA.provider + (DATA.model ? (' · ' + DATA.model) : '');
  body.appendChild(sub);

  let sectionCount = 0;

  if (DATA.context) {
    sectionCount++;
    const section = document.createElement('div');
    section.className = 'mb-4';

    const headerRow = document.createElement('div');
    headerRow.className = 'flex items-center justify-between mb-1.5';
    const headerLabel = document.createElement('div');
    headerLabel.className = 'text-[10px] font-semibold tracking-wide uppercase '
      + 'text-gray-400 dark:text-gray-500';
    headerLabel.textContent = 'Context';
    headerRow.appendChild(headerLabel);
    if (DATA.chatId && DATA.messageId && DATA.sessionId) {
      const compactBtn = document.createElement('button');
      compactBtn.type = 'button';
      compactBtn.textContent = 'Compact';
      compactBtn.className = 'text-[10px] font-medium px-2 py-0.5 rounded-full '
        + 'border border-gray-200 dark:border-gray-700 text-gray-500 dark:text-gray-400 '
        + 'hover:text-gray-800 dark:hover:text-gray-100 hover:border-gray-300 dark:hover:border-gray-600';
      compactBtn.onclick = triggerCompact;
      headerRow.appendChild(compactBtn);
    }
    section.appendChild(headerRow);

    section.appendChild(makeBar(DATA.context.pct));
    const label = document.createElement('div');
    label.className = 'text-xs text-gray-500 dark:text-gray-400 mt-1.5';
    label.textContent = DATA.context.usedTokens + ' / ' + DATA.context.totalTokens
      + ' tokens · ' + DATA.context.pct + '%';
    section.appendChild(label);
    body.appendChild(section);
  }

  if (DATA.windows.length > 0) {
    sectionCount++;
    const section = document.createElement('div');
    section.className = 'mb-4';
    section.appendChild(sectionHeader('Rate Limits'));
    DATA.windows.forEach(function(w, i) {
      const row = document.createElement('div');
      row.className = i > 0 ? 'mt-3' : '';
      const top = document.createElement('div');
      top.className = 'flex items-center justify-between text-xs '
        + 'text-gray-600 dark:text-gray-300 mb-1';
      const labelEl = document.createElement('span');
      labelEl.textContent = w.label;
      const pctEl = document.createElement('span');
      pctEl.textContent = Math.round(100 - w.usedPercent) + '% left';
      top.appendChild(labelEl);
      top.appendChild(pctEl);
      row.appendChild(top);
      row.appendChild(makeBar(w.usedPercent));
      if (w.resetIn) {
        const reset = document.createElement('div');
        reset.className = 'text-[11px] text-gray-400 dark:text-gray-500 mt-1';
        let text = 'resets in ' + w.resetIn;
        if (w.resetAtMs) {
          // Formatted in the browser's own local timezone, not computed
          // server-side -- the gateway/OWUI container's system timezone
          // and the person actually looking at this dialog aren't
          // guaranteed to be the same, so doing this client-side is the
          // only way to get it right regardless of where either runs.
          const abs = new Date(w.resetAtMs).toLocaleTimeString([], {
            hour: '2-digit', minute: '2-digit'
          });
          text += ' · ' + abs;
        }
        reset.textContent = text;
        row.appendChild(reset);
      }
      section.appendChild(row);
    });
    body.appendChild(section);
  }

  if (DATA.goal) {
    sectionCount++;
    const section = document.createElement('div');
    section.className = 'mb-4';
    section.appendChild(sectionHeader('Goal'));
    const line = document.createElement('div');
    line.className = 'text-sm text-gray-700 dark:text-gray-200';
    line.textContent = DATA.goal.line;
    section.appendChild(line);
    if (DATA.goal.pct !== null) {
      const barWrap = document.createElement('div');
      barWrap.className = 'mt-1.5';
      barWrap.appendChild(makeBar(DATA.goal.pct));
      section.appendChild(barWrap);
    }
    body.appendChild(section);
  }

  if (sectionCount === 0) {
    const empty = document.createElement('div');
    empty.className = 'text-gray-400 dark:text-gray-500 text-xs mb-4';
    empty.textContent = 'No usage data available for this session yet.';
    body.appendChild(empty);
  }

  const footer = document.createElement('div');
  footer.className = 'text-[11px] text-gray-400 dark:text-gray-600 pt-3 '
    + 'border-t border-gray-100 dark:border-gray-800';
  footer.textContent = 'Fetched ' + DATA.fetchedAt + ' · via ' + DATA.source;
  body.appendChild(footer);
})();
"""


def _render_modal_fill_js(data: dict) -> str:
    """Fill the modal template with a single JSON blob -- never string-
    interpolate individual fields directly into the JS source. json.dumps
    always produces a syntactically valid JS object-literal expression, so
    this is the one substitution point that needs to be safe against
    whatever the gateway's numbers/text happen to contain (e.g. a goal
    description with quotes or backslashes).

    json.dumps does NOT escape "<" by default, so a value containing a
    literal "</script>" would terminate an enclosing <script> tag early if
    this code ever ends up placed into HTML rather than passed straight to
    a JS execution call -- escaping "<" to the equivalent \\u003c unicode
    escape is a no-op for JSON.parse but closes that off regardless of how
    the execute event happens to deliver this string."""
    payload = json.dumps(data).replace("<", "\\u003c")
    return _MODAL_FILL_JS_TEMPLATE.replace("__OPENCLAW_STATUS_DATA__", payload)


class Action:
    class Valves(BaseModel):
        GATEWAY_URL: str = Field(
            default="localhost:18789",
            description="OpenClaw Gateway address (host:port). Only used if "
                        "this Action ever has to open its own connection "
                        "instead of reusing the Pipe's (see module notes)."
        )
        GATEWAY_TOKEN: str = Field(
            default="",
            description="OpenClaw Gateway API token. Same fallback-only caveat as GATEWAY_URL."
        )
        DEVICE_IDENTITY: str = Field(
            default="",
            description="(Advanced) Fallback device identity JSON. Set this "
                        "to the exact same value as the Pipe's DEVICE_IDENTITY "
                        "valve so a fallback connection is recognized as the "
                        "same already-approved device, not a new pairing request."
        )
        STATE_DIR: str = Field(
            default="/data/openclaw-bridge",
            description="Must match the Pipe's STATE_DIR valve -- this is how "
                        "a fallback connection finds the Pipe's persisted "
                        "device token on disk without re-pairing."
        )
        AGENT_ID: str = Field(
            default="main",
            description="Target agent identifier -- must match the Pipe's AGENT_ID valve."
        )

    def __init__(self):
        self.valves = self.Valves()

    async def action(self, body: dict, __user__=None, __event_emitter__=None):
        """Dispatches on body["mode"]: the default ("status", or absent --
        this is what OWUI sends for the actual message-toolbar click) opens
        the dialog and shows live usage; "compact" is never sent by OWUI
        itself -- it's a synthetic marker the dialog's own in-page Compact
        button fetches back with (see the Compact button's onclick in
        _MODAL_FILL_JS_TEMPLATE), reusing this same endpoint rather than
        registering a second Action."""
        if body.get("mode") == "compact":
            return await self._run_compact(body, __user__, __event_emitter__)
        return await self._run_status(body, __user__, __event_emitter__)

    async def _run_status(self, body: dict, __user__, __event_emitter__, *, show_loading=True):
        chat_id = body.get("chat_id")
        user_id = (__user__ or {}).get("id") or "unknown"

        if not chat_id:
            await __event_emitter__({
                "type": "notification",
                "data": {"type": "error", "content": "OpenClaw status: no chat_id on this message"},
            })
            return {"status": "error", "detail": "missing chat_id"}

        # Open the dialog immediately -- before touching the network -- so
        # the click gets instant feedback (overlay + loading skeleton)
        # instead of nothing visibly happening for however long the
        # gateway round trip takes. Skipped when refreshing after a compact
        # completes (_run_compact already has the dialog open on its own
        # "Compacting..." state) -- re-showing the generic skeleton there
        # would be an unnecessary extra flash between two loading states.
        if show_loading:
            await __event_emitter__({"type": "execute", "data": {"code": _MODAL_OPEN_JS}})

        session_key = _owui_session_key(self.valves.AGENT_ID, user_id, chat_id)

        try:
            conn, source = await _get_action_connection(lambda: self.valves)
            # Raw sessions.describe/usage.status rather than emit.py's
            # _build_usage_status_lines: that helper joins context+primary
            # window into one thin combined line to fit the status UI's
            # single-line clamp (see its docstring), which is exactly the
            # constraint the dialog doesn't have -- Context and Rate Limits
            # get their own sections with individual progress bars here.
            # Still reuses emit.py's small formatting primitives
            # (_fmt_tokens, _relative_time, _format_goal_line) so text like
            # "resets in 2h05m" matches the status line's wording exactly.
            desc_task = asyncio.ensure_future(
                conn.send_request("sessions.describe", dict(key=session_key), timeout=5)
            )
            usage_task = asyncio.ensure_future(
                conn.send_request("usage.status", {}, timeout=5)
            )
            desc = await desc_task
            usage = await usage_task
        except Exception as ex:
            pipe_log(f"[status-action] fetch failed: {ex}")
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js(
                    {"error": f"Could not fetch status: {ex}"}
                )},
            })
            return {"status": "error", "detail": str(ex)}

        session_row = (desc or {}).get("session") or {}
        provider = session_row.get("modelProvider") or "?"

        context_tokens = session_row.get("contextTokens")
        total_tokens = session_row.get("totalTokens")
        context_data = None
        if context_tokens and total_tokens is not None:
            context_data = {
                "usedTokens": _fmt_tokens(total_tokens),
                "totalTokens": _fmt_tokens(context_tokens),
                "pct": round(total_tokens / context_tokens * 100, 1),
            }

        windows_data = []
        for p in (usage or {}).get("providers", []):
            if p.get("provider") != provider:
                continue
            for w in p.get("windows") or []:
                used = w.get("usedPercent")
                if used is None:
                    continue
                windows_data.append({
                    "label": w.get("label"),
                    "usedPercent": used,
                    "resetIn": _relative_time(w.get("resetAt")),
                    # Raw ms timestamp, not a server-formatted clock time --
                    # the absolute time is rendered client-side (see
                    # _MODAL_FILL_JS_TEMPLATE) so it shows in the browser's
                    # own local timezone rather than whatever timezone this
                    # container happens to be running in.
                    "resetAtMs": w.get("resetAt"),
                })
            break

        goal_data = None
        goal = session_row.get("goal")
        if goal:
            goal_line = _format_goal_line(goal)
            if goal_line:
                tokens_used = goal.get("tokensUsed")
                budget = goal.get("tokenBudget")
                goal_pct = (
                    round(tokens_used / budget * 100, 1)
                    if (tokens_used is not None and budget) else None
                )
                goal_data = {"line": goal_line, "pct": goal_pct}

        modal_data = {
            "provider": provider,
            "model": session_row.get("model") or "",
            "context": context_data,
            "windows": windows_data,
            "goal": goal_data,
            "source": source,
            "fetchedAt": time.strftime("%H:%M:%S"),
            "error": None,
            # Threaded through so the dialog's own Compact button can POST
            # back to this same Action (mode="compact") with the exact same
            # chat/message/session identity -- required so the follow-up
            # call's __event_emitter__ routes to this same open browser tab.
            # __user__ is NOT included here: OWUI resolves that itself from
            # the fetch call's own Authorization header, same as the
            # original click, so there's nothing for the client to send.
            "chatId": chat_id,
            "messageId": body.get("id"),
            "sessionId": body.get("session_id"),
            "owuiModel": body.get("model"),
        }
        pipe_log(f"[status-action] opened modal ({source}): "
                 f"context={context_data} windows={len(windows_data)} goal={bool(goal_data)}")

        await __event_emitter__({
            "type": "execute",
            "data": {"code": _render_modal_fill_js(modal_data)},
        })
        return {"status": "ok", "context": context_data, "windows": windows_data}

    async def _run_compact(self, body: dict, __user__, __event_emitter__):
        """Triggers /compact on the same session and waits for it to
        finish, then refreshes the dialog with post-compaction numbers.

        Uses chat.send(message="/compact") rather than the gateway's
        sessions.compact RPC: traced sessions.compact's handler and it
        explicitly rejects webchat-classified connections
        (rejectWebchatSessionMutation / isWebchatClient in the installed
        gateway bundle) -- and the Pipe's own connect params identify as
        client.id="webchat", so any connection this Action reuses from the
        Pipe is classified the same way. The RPC's own error message
        confirms the intended alternative: "use chat.send for
        session-scoped updates". This does mean the literal "/compact" text
        becomes a real turn in the session's stored transcript (visible to
        other surfaces that inspect that history), even though it never
        appears in OWUI's own chat bubble UI (a separate HTTP path this
        call never touches) -- a known, accepted trade-off, not an oversight.

        Polls sessions.describe for completion rather than registering a
        run consumer and reading the Pipe's event queue -- see the
        Milestone 4 plan notes for why: this only needs a boolean "still
        running" signal, not live text streaming, so the Pipe's much larger
        consumption loop (idle probes, steering, preview recovery) would be
        a lot of machinery for a narrow need.
        """
        chat_id = body.get("chat_id")
        user_id = (__user__ or {}).get("id") or "unknown"

        if not chat_id:
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js({"error": "Missing chat_id"})},
            })
            return {"status": "error", "detail": "missing chat_id"}

        session_key = _owui_session_key(self.valves.AGENT_ID, user_id, chat_id)

        try:
            conn, source = await _get_action_connection(lambda: self.valves)
        except Exception as ex:
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js({"error": f"Could not connect: {ex}"})},
            })
            return {"status": "error", "detail": str(ex)}

        if conn.active_run_id_for_session(session_key):
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js({
                    "error": "A response is currently in progress — wait for "
                             "it to finish before compacting."
                })},
            })
            return {"status": "error", "detail": "session busy"}

        # Immediate, unambiguous visual feedback -- compaction can take a
        # while (it's an LLM summarization call), so the dialog needs a
        # definitive "in progress" state, not a skeleton that looks like
        # it's about to finish in a second.
        await __event_emitter__({"type": "execute", "data": {"code": _MODAL_COMPACTING_JS}})

        try:
            compact_params = _owui_chat_send_params(
                session_key=session_key,
                message="/compact",
                idempotency_key=f"compact-{chat_id}-{time.time()}",
                owui_chat_id=chat_id,
                owui_user_id=user_id,
            )
            # Explicit, not relying on the gateway's own default for an
            # omitted field: this compact run should never trigger outbound
            # delivery to other configured channels (Slack/Discord/etc.) --
            # same reasoning gateway.py's existing send_stop already applies
            # to its own chat.send("/stop") call.
            compact_params["deliver"] = False
            send_resp = await conn.send_request("chat.send", compact_params, timeout=30)
        except Exception as ex:
            pipe_log(f"[status-action] compact chat.send failed: {ex}")
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js({"error": f"Could not start compact: {ex}"})},
            })
            return {"status": "error", "detail": str(ex)}

        pipe_log(f"[status-action] compact started, runId={send_resp.get('runId')}")

        deadline = time.time() + 180  # matches `openclaw sessions compact`'s own default RPC timeout
        status = None
        while time.time() < deadline:
            await asyncio.sleep(1.5)
            try:
                desc = await conn.send_request("sessions.describe", dict(key=session_key), timeout=8)
            except Exception as ex:
                pipe_log(f"[status-action] compact poll failed: {ex}")
                continue
            status = ((desc or {}).get("session") or {}).get("status")
            if status in ("done", "failed", "cancelled"):
                break

        if status not in ("done", "failed", "cancelled"):
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js(
                    {"error": "Compact timed out — it may still finish in the background."}
                )},
            })
            return {"status": "error", "detail": "timeout"}

        if status != "done":
            await __event_emitter__({
                "type": "execute",
                "data": {"code": _render_modal_fill_js({"error": f"Compact {status}."})},
            })
            return {"status": "error", "detail": status}

        pipe_log("[status-action] compact done, refreshing status")
        return await self._run_status(body, __user__, __event_emitter__, show_loading=False)
