"""
title: OpenClaw Thinking
author: Eliav
author_url: https://github.com/Eliav2
project_url: https://github.com/Eliav2/openclaw-openwebui-integration
version: 0.7.0
license: MIT
required_open_webui_version: 0.10.2
description: Per-chat thinking / reasoning-effort control for the OpenClaw Gateway pipe. Adds a toggle to the message input and a level dropdown, and writes the standard reasoning_effort field the pipe reads.

OpenClaw Thinking Filter for Open WebUI
=======================================

Sets how hard the agent thinks before answering, per chat, from the message
input row rather than from a settings page.

Why a filter
------------
Open WebUI has no extension point for adding a control to the message input
box itself. A Filter with ``toggle = True`` is the one thing that renders
there, so the toggle is the entry point and the level lives in the filter's
per-user valves.

Single source of truth
----------------------
The level is written to ``body["reasoning_effort"]``, which is the same field
Open WebUI's own Advanced Params "Reasoning Effort" control writes. Setting
either one moves the same value, and this filter shows whatever Advanced
Params already set. When the toggle is off, the filter does not touch the
field at all, so Advanced Params keeps working exactly as before.

Nothing is sent when nothing is chosen. "default" means the pipe omits the
field entirely and the agent's own configured thinking level applies.

Which levels appear
-------------------
The dropdown lists only levels that a model on your gateway actually supports.
The pipe writes the ladders it sees to ``<STATE_DIR>/thinking-ladders.json``
and this filter reads that file when Open WebUI loads it. Providers differ:
an Anthropic model may offer ``off, minimal, low, medium, high`` while a
DeepSeek model also offers ``xhigh`` and ``max``. Until the pipe has run at
least once, a conservative built-in list is used.

Because Open WebUI builds a valve dropdown once, from the class, the list is
the union across models rather than per selected model. The pipe does the
per-model part: it checks the chosen level against the live session ladder and
clamps down to the nearest supported one, telling you in the chat when it did.

Installation
------------
1. In Open WebUI, go to Admin Panel > Functions
2. Click "+" and choose "Create a function"
3. Set type to "filter", id to "openclaw_thinking"
4. Paste the entire contents of this file
5. Save and turn on "Active"
6. Leave "Global" OFF unless every model you use is an OpenClaw pipe model.
   Attach it to the OpenClaw models instead: Workspace > Models > (model) >
   Filters. A global filter runs on every chat with every model, and this one
   writes reasoning_effort, which other pipes may interpret differently.

Then open a chat, click the Thinking toggle under the message box, and pick a
level in Chat Controls > Valves.
"""

# ==========================================================================
# AUTO-GENERATED by build.py from src/openclaw_pipe_pkg/ -- DO NOT EDIT HERE.
# Edit the fragments under src/openclaw_pipe_pkg/ and re-run: python3 build.py
# ==========================================================================


# --- thinking --------------------------------------------------------------
# Shared by BOTH the Thinking filter and the Pipe: the filter offers the levels
# and the pipe enforces them against the live session ladder, so the ranks and
# the clamping rule have to be one implementation, not two that agree today.
#
# Deliberately has no imports, no classes, and no module-level names beyond the
# five below. It is concatenated into the Pipe artifact, where every name in it
# lands in the same flat namespace as every other fragment: a helper named like
# one of the pipe's own (a `_state_dir`, say) would silently shadow it
# depending on fragment order. Filter-only helpers live in `thinking_filter`
# for exactly that reason.

# ---------------------------------------------------------------------------
# Levels
# ---------------------------------------------------------------------------

# Ranks mirror the gateway's own table (off is genuinely a level, not an
# absence). Used to order the dropdown and to clamp downward, never upward:
# asking for less thinking than requested is a safe degradation, asking for
# more is a surprise on someone's bill.
LEVEL_RANKS = {
    "off": 0,
    "minimal": 10,
    "low": 20,
    "medium": 30,
    "adaptive": 30,
    "high": 40,
    "xhigh": 60,
    "max": 70,
    "ultra": 80,
}

# The sentinel meaning "do not send the field at all". Distinct from "off",
# which is an explicit instruction to not think. "default" leaves the agent's
# own configured level alone; "off" overrides it.
UNSET = "default"

# Used until the pipe has run once and written a real ladder cache. Every
# provider observed supports at least these, so nothing here can be a lie.
FALLBACK_LEVELS = ["off", "minimal", "low", "medium", "high"]

LADDER_CACHE_NAME = "thinking-ladders.json"

# The Gateway's rejection lists LABELS, not ids, and for most profiles the two
# are identical (`label: id`). The one divergence is the binary profile, which
# labels `low` as "on". Mapping it back is the difference between learning a
# model's real two-level ladder and learning a one-level lie.
LEVEL_LABEL_ALIASES = {"on": "low"}

# The exact anchors of the Gateway's hard validation error, e.g.:
#   Thinking level "high" is not supported for claude-cli/claude-opus-5. Use one of: off.
# All three must be present and in order. That is deliberately at least as
# narrow as matching the whole sentence: it can never fire on genuine assistant
# text that happens to discuss thinking levels.
_REJECT_HEAD = 'Thinking level "'
_REJECT_MID = '" is not supported for '
_REJECT_TAIL = ". Use one of: "


def parse_thinking_rejection(text):
    """Read the Gateway's own rejection as an authoritative per-model ladder.

    This exists because `sessions.describe` cannot be trusted for this. Describe
    builds its ladder with no model catalog in scope, so `resolveThinkingProfile`
    never sees the catalog's `reasoning: false` and falls through to the generic
    base profile -- it reported all 8 levels for `claude-cli/claude-opus-5`,
    whose real ladder is `["off"]`. The send path resolves the same question
    WITH the catalog and rejects. So the rejection is the only place the truth
    is stated, and throwing it away is what made this misfire once per turn
    forever instead of once per model.

    Returns None when `text` is not that rejection. Otherwise a dict:
    `{"level": requested, "model": "provider/model", "levels": [ids]}`.
    `levels` may be empty if every listed label is unrecognised -- the caller
    still learns which model rejected which level, so it must check for None
    rather than for falsiness.

    Pure string parsing on purpose: this fragment is shared with the Thinking
    filter, which imports nothing (not even `re`) so that a filter running on
    every message can never fail on an import it did not need.
    """
    if not text:
        return None
    head = text.find(_REJECT_HEAD)
    if head < 0:
        return None
    level_start = head + len(_REJECT_HEAD)
    mid = text.find(_REJECT_MID, level_start)
    if mid < 0:
        return None
    tail = text.find(_REJECT_TAIL, mid)
    if tail < 0:
        return None

    level = text[level_start:mid].strip().lower()
    model = text[mid + len(_REJECT_MID):tail].strip()
    if not level or not model or " " in model:
        # A model ref never contains a space. Anything that does means the
        # anchors matched something that merely reads like the rejection.
        return None

    listed = text[tail + len(_REJECT_TAIL):]
    stop = listed.find(".")
    if stop >= 0:
        listed = listed[:stop]
    levels = []
    for token in listed.split(","):
        name = token.strip().lower()
        name = LEVEL_LABEL_ALIASES.get(name, name)
        if name in LEVEL_RANKS and name not in levels:
            levels.append(name)
    levels.sort(key=lambda lv: LEVEL_RANKS[lv])
    return {"level": level, "model": model, "levels": levels}


def clamp_to_ladder(level, ladder):
    """Fit a requested level to what a model actually supports.

    Returns (resolved_level, note). `note` is None when the request went
    through untouched, otherwise a short human sentence explaining what
    changed, which the caller is expected to show rather than swallow.

    Clamping is always downward to the nearest supported rank. If the model
    supports nothing at or below the request (a ladder of only higher levels,
    which no observed provider has, but which costs nothing to handle), the
    lowest supported level is used.
    """
    if not level or level == UNSET:
        return None, None
    if not ladder:
        # No ladder known: pass the request through and let the gateway rule on
        # it. Silently dropping a level the user explicitly picked is worse.
        return level, None
    if level in ladder:
        return level, None

    want = LEVEL_RANKS.get(level)
    if want is None:
        return None, f"Unknown thinking level {level!r}, ignoring it."

    at_or_below = [lv for lv in ladder if LEVEL_RANKS.get(lv, 0) <= want]
    if at_or_below:
        best = max(at_or_below, key=lambda lv: LEVEL_RANKS.get(lv, 0))
    else:
        best = min(ladder, key=lambda lv: LEVEL_RANKS.get(lv, 0))
    return best, (
        f"This model does not support thinking level {level!r}, "
        f"using {best!r} instead."
    )


# --- thinking_filter -------------------------------------------------------
# The Filter class and its pydantic surface. Split from `thinking` so the Pipe
# can reuse the ranks and the clamp without also inheriting a Filter class it
# must not expose.
#
# pydantic is the only non-stdlib import here, and Open WebUI ships it. This
# deliberately does NOT reuse the pipe's _prelude, which pulls in websockets and
# cryptography: a filter runs on every message, and one that cannot import takes
# the whole chat down with it. A transport dependency is not worth that risk for
# a control that only writes one dict key.

import json
import os
from typing import Optional

from pydantic import BaseModel, Field, create_model


# ---------------------------------------------------------------------------
# Reading the ladder cache
# ---------------------------------------------------------------------------

def _state_dir():
    """Same default and env override as the pipe, without importing it.

    Read-only here, so unlike the pipe this never creates or falls back to a
    writable directory: a missing directory just means no cache yet.
    """
    return os.environ.get("OPENCLAW_BRIDGE_STATE_DIR") or "/data/openclaw-bridge"


def _read_ladder_cache(path=None):
    """Return the level ids the pipe has actually seen a gateway offer.

    The cache is written by the pipe (see gateway.py) as::

        {"levels": ["off", "minimal", ...], "updated": 1786784049}

    Anything unreadable, malformed, or empty falls back rather than raising:
    a broken cache must degrade to a shorter dropdown, never to a broken chat.
    """
    path = path or os.path.join(_state_dir(), LADDER_CACHE_NAME)
    try:
        with open(path) as fh:
            data = json.load(fh)
    except Exception:
        return None
    if not isinstance(data, dict):
        return None
    levels = data.get("levels")
    if not isinstance(levels, list):
        return None
    known = [str(x) for x in levels if str(x) in LEVEL_RANKS]
    return known or None


def available_levels(path=None):
    """The dropdown contents: UNSET first, then real levels ordered by rank.

    This is the union across the models the gateway knows about, not the ladder
    of the currently selected model. Open WebUI builds a valve dropdown once,
    from the class, so it cannot vary per message. The pipe closes that gap by
    clamping against the live session ladder at send time and saying so.
    """
    levels = _read_ladder_cache(path) or FALLBACK_LEVELS
    ordered = sorted(set(levels), key=lambda lv: (LEVEL_RANKS[lv], lv))
    return [UNSET] + ordered


# ---------------------------------------------------------------------------
# Filter
# ---------------------------------------------------------------------------

# Black stroke on purpose: Open WebUI renders this via <img src=...> and applies
# `dark:invert-[80%]` to any `data:image/svg` icon, so currentColor never
# resolves and a themed stroke shows up invisible in one of the two themes.
ICON = (
    "data:image/svg+xml;charset=utf-8,"
    "%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2024%2024'%20"
    "fill='none'%20stroke='%23000'%20stroke-width='1.8'%20stroke-linecap='round'%20"
    "stroke-linejoin='round'%3E%3Cpath%20d='M12%203a5.5%205.5%200%200%200-3.2%209.9V15h6.4v-2.1"
    "A5.5%205.5%200%200%200%2012%203z'/%3E%3Cpath%20d='M9.5%2018h5'/%3E%3Cpath%20d='M10.5%2021h3'/%3E%3C/svg%3E"
)


def _build_user_valves(levels):
    """Build the UserValves model with the dropdown baked in.

    A pydantic Literal is fixed when the class is defined, so the choices have
    to be known at import time. create_model is what lets the list come from
    the gateway's real ladders instead of being hardcoded here.
    """
    return create_model(
        "UserValves",
        level=(
            str,
            Field(
                default=UNSET,
                description=(
                    "How hard the agent thinks before answering. "
                    "'" + UNSET + "' sends nothing and leaves the agent's own "
                    "configured level alone. Levels a model does not support "
                    "are clamped down, and the chat says so."
                ),
                json_schema_extra={"enum": levels},
            ),
        ),
        __base__=BaseModel,
    )


class Filter:
    class Valves(BaseModel):
        priority: int = Field(
            default=0,
            description="Filter execution order. Lower runs earlier.",
        )
        override_advanced_params: bool = Field(
            default=True,
            description=(
                "When on, the level picked here wins over Open WebUI's own "
                "Advanced Params reasoning effort. Turn it off to let Advanced "
                "Params win and use this toggle only to enable thinking."
            ),
        )

    UserValves = _build_user_valves(available_levels())

    def __init__(self):
        self.valves = self.Valves()
        # Open WebUI caches the Filter *instance*, not the module, so `toggle`
        # and `icon` have to be instance attributes. Set at class level they are
        # invisible to get_filter_items_from_module() and the row silently never
        # renders, which reads exactly like the filter not being installed.
        self.toggle = True
        self.icon = ICON

    def inlet(self, body: dict, __user__: Optional[dict] = None) -> dict:
        """Write the chosen level into the field the pipe reads.

        `body["reasoning_effort"]` is the single source of truth. Open WebUI's
        Advanced Params control writes the same key, so the two controls move
        one value instead of racing over two.

        Reached only when the toggle is on: Open WebUI does not run a toggled
        filter's inlet otherwise. So an untouched chat behaves exactly as if
        this filter were not installed.
        """
        if not isinstance(body, dict):
            return body

        user_valves = (__user__ or {}).get("valves")
        level = getattr(user_valves, "level", None)
        if isinstance(user_valves, dict):
            level = user_valves.get("level")

        if not level or level == UNSET:
            # Nothing chosen. Leave whatever Advanced Params set, including
            # leaving the key absent, so the pipe omits it downstream.
            return body

        if body.get("reasoning_effort") and not self.valves.override_advanced_params:
            return body

        body["reasoning_effort"] = level
        return body
